//
//  UIMenuItem+Extra.h
//  JobsByOCPods
//
//  Created by Jobs on 2026年5月13日，星期三.
//

#ifndef JOBS_HEADER_GUARD_UIMENUITEM_EXTRA_1BFE345E53
#define JOBS_HEADER_GUARD_UIMENUITEM_EXTRA_1BFE345E53

#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

@interface UIMenuItem (Extra)

@end

NS_ASSUME_NONNULL_END
#endif /* JOBS_HEADER_GUARD_UIMENUITEM_EXTRA_1BFE345E53 */
