//
//  CMMotionManager+DSL.h
//  JobsOCDSL
//
//  Created by Jobs on 2026年7月13日，星期一.
//

#import <CoreMotion/CoreMotion.h>

#if __has_include(<JobsBlock/JobsBlock.h>)
#import <JobsBlock/JobsBlock.h>
#else
#import "JobsBlock.h"
#endif

NS_ASSUME_NONNULL_BEGIN

@interface CMMotionManager (DSL)

+(JobsRetCMMotionManagerByVoidBlock _Nonnull)byMotionManager;
-(JobsRetCMMotionManagerByTimeIntervalBlock _Nonnull)byAccelerometerUpdateInterval;
-(JobsRetCMMotionManagerByTimeIntervalBlock _Nonnull)byGyroUpdateInterval;
-(JobsRetCMMotionManagerByTimeIntervalBlock _Nonnull)byMagnetometerUpdateInterval;
-(JobsRetCMMotionManagerByTimeIntervalBlock _Nonnull)byDeviceMotionUpdateInterval;
-(JobsRetCMMotionManagerByBOOLBlock _Nonnull)byShowsDeviceMovementDisplay;
-(JobsRetCMMotionManagerByVoidBlock _Nonnull)byStartAccelerometerUpdates;
-(JobsRetCMMotionManagerByOperationQueueAndAccelerometerHandlerBlock _Nonnull)byStartAccelerometerUpdatesToQueue;
-(JobsRetCMMotionManagerByVoidBlock _Nonnull)byStopAccelerometerUpdates;
-(JobsRetCMMotionManagerByVoidBlock _Nonnull)byStartGyroUpdates;
-(JobsRetCMMotionManagerByOperationQueueAndGyroHandlerBlock _Nonnull)byStartGyroUpdatesToQueue;
-(JobsRetCMMotionManagerByVoidBlock _Nonnull)byStopGyroUpdates;
-(JobsRetCMMotionManagerByVoidBlock _Nonnull)byStartMagnetometerUpdates;
-(JobsRetCMMotionManagerByOperationQueueAndMagnetometerHandlerBlock _Nonnull)byStartMagnetometerUpdatesToQueue;
-(JobsRetCMMotionManagerByVoidBlock _Nonnull)byStopMagnetometerUpdates;
-(JobsRetCMMotionManagerByVoidBlock _Nonnull)byStartDeviceMotionUpdates;
-(JobsRetCMMotionManagerByOperationQueueAndDeviceMotionHandlerBlock _Nonnull)byStartDeviceMotionUpdatesToQueue;
-(JobsRetCMMotionManagerByAttitudeReferenceFrameBlock _Nonnull)byStartDeviceMotionUpdatesUsingReferenceFrame;
-(JobsRetCMMotionManagerByReferenceFrameOperationQueueAndDeviceMotionHandlerBlock _Nonnull)byStartDeviceMotionUpdatesUsingReferenceFrameToQueue;
-(JobsRetCMMotionManagerByVoidBlock _Nonnull)byStopDeviceMotionUpdates;
-(JobsRetCMMotionManagerByVoidBlock _Nonnull)byStopAllUpdates;

@end

NS_ASSUME_NONNULL_END
