//
//  JobsTabBarSettingVC.h
//  JobsBaseUI
//
//  Created by Jobs on 2026年5月13日，星期三.
//

#ifndef JOBS_HEADER_GUARD_JOBSTABBARSETTINGVC_B2ADDCC22A
#define JOBS_HEADER_GUARD_JOBSTABBARSETTINGVC_B2ADDCC22A

#import "JobsNavSettingVC.h"

NS_ASSUME_NONNULL_BEGIN

@interface JobsTabBarSettingVC : JobsNavSettingVC

@end

NS_ASSUME_NONNULL_END
#endif /* JOBS_HEADER_GUARD_JOBSTABBARSETTINGVC_B2ADDCC22A */
