//
//  FSCalendarSeparatorDecorationView.h
//  FSCalendar
//
//  Created by Jobs on 2026年5月13日，星期三.
//

#ifndef JOBS_FSCALENDAR_CORE_FSCALENDARSEPARATORDECORATIONVIEW_FSCALENDARSEPARATORDECORATIONVIEW_H
#define JOBS_FSCALENDAR_CORE_FSCALENDARSEPARATORDECORATIONVIEW_FSCALENDARSEPARATORDECORATIONVIEW_H

#pragma once

#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

@interface FSCalendarSeparatorDecorationView : UICollectionReusableView

@end

NS_ASSUME_NONNULL_END

#endif /* JOBS_FSCALENDAR_CORE_FSCALENDARSEPARATORDECORATIONVIEW_FSCALENDARSEPARATORDECORATIONVIEW_H */
