//
//  SPAlertControllerConfig+DSL.h
//  JobsOCBaseConfigDemo
//
//  Created by Jobs on 2026年6月4日，星期四.
//

#ifndef JOBS_HEADER_GUARD_SPALERTCONTROLLERCONFIG_DSL_3AEDC79A6BB7A081
#define JOBS_HEADER_GUARD_SPALERTCONTROLLERCONFIG_DSL_3AEDC79A6BB7A081

#import "JobsModel.h"

#import "JobsBlock.h"

NS_ASSUME_NONNULL_BEGIN

@interface SPAlertControllerConfig (DSL)

-(JobsRetSPAlertControllerConfigByNSObject_SPAlertControllerInitTypeBlock _Nonnull)bySPAlertControllerInitType;
-(JobsRetSPAlertControllerConfigByStrBlock _Nonnull)byTitle;
-(JobsRetSPAlertControllerConfigByStrBlock _Nonnull)byMessage;
-(JobsRetSPAlertControllerConfigByUIViewPointerBlock _Nonnull)byCustomAlertView;
-(JobsRetSPAlertControllerConfigByUIViewPointerBlock _Nonnull)byCustomHeaderView;
-(JobsRetSPAlertControllerConfigByUIViewPointerBlock _Nonnull)byCustomActionSequenceView;
-(JobsRetSPAlertControllerConfigByNSIntegerBlock _Nonnull)byPreferredStyle;
-(JobsRetSPAlertControllerConfigByNSIntegerBlock _Nonnull)byAnimationType;
-(JobsRetSPAlertControllerConfigByUIViewControllerPointerBlock _Nonnull)byTargetVC;
-(JobsRetSPAlertControllerConfigByIDBlock _Nonnull)byFuncInWhere;
-(JobsRetSPAlertControllerConfigByBOOLBlock _Nonnull)byAnimated;
-(JobsRetSPAlertControllerConfigByNSArrayNSStringPointerPointerBlock _Nonnull)byAlertActionTitleArr;
-(JobsRetSPAlertControllerConfigByNSArrayNSNumberPointerPointerBlock _Nonnull)byAlertActionStyleArr;
-(JobsRetSPAlertControllerConfigByNSArrayNSStringPointerPointerBlock _Nonnull)byAlertBtnActionArr;
-(JobsRetSPAlertControllerConfigByNSArrayNSMutableArrayPointerPointerBlock _Nonnull)byParametersArr;

@end

NS_ASSUME_NONNULL_END
#endif /* JOBS_HEADER_GUARD_SPALERTCONTROLLERCONFIG_DSL_3AEDC79A6BB7A081 */
