#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSInteger, DKDeviceType) {
    DKDeviceTypeUnknown = 0,
    DKDeviceTypeSimulator,
    DKDeviceTypeiPodTouch5,
    DKDeviceTypeiPodTouch6,
    DKDeviceTypeiPodTouch7,
    DKDeviceTypeiPhone4,
    DKDeviceTypeiPhone4s,
    DKDeviceTypeiPhone5,
    DKDeviceTypeiPhone5c,
    DKDeviceTypeiPhone5s,
    DKDeviceTypeiPhone6,
    DKDeviceTypeiPhone6Plus,
    DKDeviceTypeiPhone6s,
    DKDeviceTypeiPhone6sPlus,
    DKDeviceTypeiPhone7,
    DKDeviceTypeiPhone7Plus,
    DKDeviceTypeiPhoneSE,
    DKDeviceTypeiPhone8,
    DKDeviceTypeiPhone8Plus,
    DKDeviceTypeiPhoneX,
    DKDeviceTypeiPhoneXS,
    DKDeviceTypeiPhoneXSMax,
    DKDeviceTypeiPhoneXR,
    DKDeviceTypeiPhone11,
    DKDeviceTypeiPhone11Pro,
    DKDeviceTypeiPhone11ProMax,
    DKDeviceTypeiPhoneSE2,
    DKDeviceTypeiPhone12,
    DKDeviceTypeiPhone12Mini,
    DKDeviceTypeiPhone12Pro,
    DKDeviceTypeiPhone12ProMax,
    DKDeviceTypeiPhone13,
    DKDeviceTypeiPhone13Mini,
    DKDeviceTypeiPhone13Pro,
    DKDeviceTypeiPhone13ProMax,
    DKDeviceTypeiPhoneSE3,
    DKDeviceTypeiPhone14,
    DKDeviceTypeiPhone14Plus,
    DKDeviceTypeiPhone14Pro,
    DKDeviceTypeiPhone14ProMax,
    DKDeviceTypeiPhone15,
    DKDeviceTypeiPhone15Plus,
    DKDeviceTypeiPhone15Pro,
    DKDeviceTypeiPhone15ProMax,
    DKDeviceTypeiPhone16,
    DKDeviceTypeiPhone16Plus,
    DKDeviceTypeiPhone16Pro,
    DKDeviceTypeiPhone16ProMax,
    DKDeviceTypeiPad2,
    DKDeviceTypeiPad3,
    DKDeviceTypeiPad4,
    DKDeviceTypeiPadAir,
    DKDeviceTypeiPadAir2,
    DKDeviceTypeiPad5,
    DKDeviceTypeiPad6,
    DKDeviceTypeiPadAir3,
    DKDeviceTypeiPad7,
    DKDeviceTypeiPad8,
    DKDeviceTypeiPad9,
    DKDeviceTypeiPad10,
    DKDeviceTypeiPadAir4,
    DKDeviceTypeiPadAir5,
    DKDeviceTypeiPadAir11M2,
    DKDeviceTypeiPadAir13M2,
    DKDeviceTypeiPadMini,
    DKDeviceTypeiPadMini2,
    DKDeviceTypeiPadMini3,
    DKDeviceTypeiPadMini4,
    DKDeviceTypeiPadMini5,
    DKDeviceTypeiPadMini6,
    DKDeviceTypeiPadPro9Inch,
    DKDeviceTypeiPadPro12Inch,
    DKDeviceTypeiPadPro12Inch2,
    DKDeviceTypeiPadPro10Inch,
    DKDeviceTypeiPadPro11Inch,
    DKDeviceTypeiPadPro12Inch3,
    DKDeviceTypeiPadPro11Inch2,
    DKDeviceTypeiPadPro12Inch4,
    DKDeviceTypeiPadPro11Inch3,
    DKDeviceTypeiPadPro12Inch5,
    DKDeviceTypeiPadPro11Inch4,
    DKDeviceTypeiPadPro12Inch6,
    DKDeviceTypeiPadPro11M4,
    DKDeviceTypeiPadPro13M4,
    DKDeviceTypehomePod,
    DKDeviceTypeappleTVHD,
    DKDeviceTypeappleTV4K,
    DKDeviceTypeappleTV4K2,
    DKDeviceTypeappleTV4K3,
    DKDeviceTypeappleWatchSeries0_38mm,
    DKDeviceTypeappleWatchSeries0_42mm,
    DKDeviceTypeappleWatchSeries1_38mm,
    DKDeviceTypeappleWatchSeries1_42mm,
    DKDeviceTypeappleWatchSeries2_38mm,
    DKDeviceTypeappleWatchSeries2_42mm,
    DKDeviceTypeappleWatchSeries3_38mm,
    DKDeviceTypeappleWatchSeries3_42mm,
    DKDeviceTypeappleWatchSeries4_40mm,
    DKDeviceTypeappleWatchSeries4_44mm,
    DKDeviceTypeappleWatchSeries5_40mm,
    DKDeviceTypeappleWatchSeries5_44mm,
    DKDeviceTypeappleWatchSeries6_40mm,
    DKDeviceTypeappleWatchSeries6_44mm,
    DKDeviceTypeappleWatchSE_40mm,
    DKDeviceTypeappleWatchSE_44mm,
    DKDeviceTypeappleWatchSeries7_41mm,
    DKDeviceTypeappleWatchSeries7_45mm,
    DKDeviceTypeappleWatchSeries8_41mm,
    DKDeviceTypeappleWatchSeries8_45mm,
    DKDeviceTypeappleWatchSE2_40mm,
    DKDeviceTypeappleWatchSE2_44mm,
    DKDeviceTypeappleWatchUltra,
    DKDeviceTypeappleWatchSeries9_41mm,
    DKDeviceTypeappleWatchSeries9_45mm,
    DKDeviceTypeappleWatchUltra2,
    DKDeviceTypeappleWatchSeries10_42mm,
    DKDeviceTypeappleWatchSeries10_46mm,
};

FOUNDATION_EXPORT NSString *DKDeviceTypeDescription(DKDeviceType type,
                                                   id _Nullable simulatedDevice,
                                                   NSString * _Nullable unknownIdentifier);

/// Returns DKApplePencilSupport bitmask (defined in DKDevice.h / DKApplePencil.h)
FOUNDATION_EXPORT NSUInteger DKApplePencilSupportForType(DKDeviceType type,
                                                         id _Nullable simulatedDevice,
                                                         NSString * _Nullable unknownIdentifier);

NS_ASSUME_NONNULL_END
