//
//  UIScrollView+FDFullscreenPopGesture.h
//  FDFullscreenPopGesture
//
//  Created by Jobs on 2026年5月13日，星期三.
//

#ifndef JOBS_HEADER_GUARD_UISCROLLVIEW_FDFULLSCREENPOPGESTURE_0EEC650902
#define JOBS_HEADER_GUARD_UISCROLLVIEW_FDFULLSCREENPOPGESTURE_0EEC650902

#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

@interface UIScrollView (FDFullscreenPopGesture)

@end

NS_ASSUME_NONNULL_END
#endif /* JOBS_HEADER_GUARD_UISCROLLVIEW_FDFULLSCREENPOPGESTURE_0EEC650902 */
