//
//  Demos.h
//  JobsOCBaseConfigDemo
//
//  Created by Jobs on 2026年5月28日，星期四.
//

#ifndef Demos_h
#define Demos_h
/// 相关功能模块组测试控制器
#import "JobsProgressVC.h"
#import "A_VC.h"
#import "TransparentRegionVC.h"
#import "DynamicViewTestVC.h"
#import "TestIrregularViewTestVC.h"
#import "JobsZFPlayerDemoListVC.h"

#import "JobsAppDoor.h"

#import "JobsAppDoorDemoListVC.h"
#import "JobsCommentVC.h"
#import "JobsOCCommentDemoVC.h"
#import "JobsIMShowVC.h"
#import "JobsOCSearcherDemoVC.h"
#import "JobsOCMarkdownDocumentsDemoVC.h"
#import "TestLabelVC.h"
#import "JobsAnimatedNumberLabelDemoVC.h"
#import "JobsTimerDemoListVC.h"
#import "JobsBluetoothDemoVC.h"
#import "JobsCoreMotionDemoVC.h"
#import "JobsOCSceneDelegateDemoVC.h"
#import "JobsScreenshotTipsDemoVC.h"
#import "JobsScreenshotProtectionDemoVC.h"
#import "JobsOCAudioRecorderDemoVC.h"
#import "JobsTimerVC.h"
#import "JobsCountdownButtonDemoVC.h"
#import "JobsCountdownLayerDemoVC.h"
#import "JobsLongPressLikeDemoVC.h"
#import "JobsSysProgressDemoVC.h"
#import "JobsProgressDemoVC.h"
#import "JobsOCTimerMgrDemoVC.h"
#import "JobsRedPacketRainDemoVC.h"
#import "JobsMultiTimerTableDemoVC.h"
#import "JobsMarqueeViewDemoVC.h"
#import "JobsDropDownListVC.h"
#import "JobsLiveCommentDemoVC.h"
#import "JobsLiveStreamDemoVC.h"
#import "JobsMosaicDemoListVC.h"
#import "JobsIconfontDemoVCs.h"
#import "JobsButtonCoverCellDemoListVC.h"
#import "JobsSphereDemoVC.h"
#import "YTKNetworkStudyVC.h"
#import "JobsWebSocketDemoVC.h"
#import "CoreTextLearningVC.h"
#import "JXCategoryPopupVC.h"
#import "UITableViewCellEditorVC.h"
#import "JobsSettingGestureVC.h"
#import "CXBVC.h"
#import "OCDynamicRegisterVC.h"
#import "ProtocolKitVC.h"
#import "JXCategoryViewWithHeaderViewVC.h"
#import "UILabelWordRotatingVC.h"
#import "JXCategoryViewVerticalShowVC.h"
#import "JobsVerticalMenuMainVC.h"
#import "JobsLinkageMenuViewDemoVC.h"
#import "JobsOCRefresherDemoVC.h"
#import "JobsDouyinRefreshDemoVC.h"
#import "TestBaseLabelVC.h"
#import "RandomTestVC.h"
#import "CustomTableViewCellVC.h"
#import "CustomBtnVC.h"
#import "GXCardViewDemoVC.h"
#import "JobsWalletVC.h"
#import "JobsScrollViewVC.h"
#import "JobsPresentingVC.h"
#import "JobsPostVC.h"
#import "JobsShootingVC.h"
#import "MasonryVC.h"
#import "UITBVCellFoldVC.h"
#import "PicToStrStoreVC.h"
#import "CtrlClipboardCueVC.h"

//#import "TextureDemoVC.h"
#import "LocalNotificationsVC.h"
#import "ExcelVC.h"
#import "JobsOCExcelDemoVC.h"
#import "JobsHandwritingDemoVC.h"
#import "JobsViewPushDemoVC.h"
#import "JobsSideDrawerDemoVC.h"
#import "CompressStrVC.h"
#import "AppIconSwitchingVC.h"
#import "MyTableTableVC.h"
#import "LandscapeSwitchVC.h"
#import "WidgetVC.h"
#import "HotRefreshVC.h"
#import "FMDB_VC.h"
#import "Realm_VC.h"
#import "LotteryVC.h"
#import "PointLabTestVC.h"
#import "CalendarVC.h"                     // 日历功能
#import "NSProxyDemoVC.h"
#import "JobsNavigationDemoVC.h"
#import "SlideToUnlockDemoVC.h"
#import "JobsClockDemoVC.h"
#import "JobsImageRotationDemoVC.h"
#import "JobsTabBarCtrlDemoVC.h"
#import "JobsOCKeyboardMgrDemoVC.h"
#import "JobsOCNumberStepperDemoVC.h"
#import "JobsOCGraphicCaptchaDemoVC.h"
#import "JobsQRCodeDemoVC.h"
#import "JobsCNIDDemoVC.h"
#import "JobsOCSkeletonViewDemoVC.h"
#import "JobsOCCrashLogVC.h"
#import "JobsSwiftParityMomentsPreviewDemoVC.h"
#import "JobsSwiftParityThrottleDebounceDemoVC.h"
#import "JobsSwiftParityTaskCenterDemoVC.h"
#import "JobsSwiftParityAnimatedButtonNumberDemoVC.h"
#import "JobsSwiftParityDashboardDemoVC.h"
#import "JobsSwiftParityControlEventsDemoVC.h"
#import "JobsSwiftParityTraitChangeDemoVC.h"
#import "JobsSwiftParityEditProfileDemoVC.h"
#import "JobsSwiftParityPDFDemoVC.h"
#import "JobsSwiftParityToastDemoVC.h"
#import "JobsSwiftParityAlertDemoVC.h"
#import "JobsSwiftParityOpenDemoVC.h"
#import "JobsSwiftParitySnowflakeDemoVC.h"

#if __has_include(<JobsOCCountryCodeCtrl/JobsOCCountryCodeCtrlHeader.h>)
#import <JobsOCCountryCodeCtrl/JobsOCCountryCodeCtrlHeader.h>
#else
#import "JobsOCCountryCodeCtrlHeader.h"
#endif

#if __has_include(<JobsOCVideoRecorder/JobsOCVideoRecorder.h>)
#import <JobsOCVideoRecorder/JobsOCVideoRecorder.h>
#else
#import "JobsOCVideoRecorder.h"
#endif

#endif /* Demos_h */
