//
//  JobsCustomTabBarButton.h
//  JobsOCTools
//
//  Created by Jobs on 2026年5月13日，星期三.
//

#ifndef JOBS_HEADER_GUARD_JOBSCUSTOMTABBARBUTTON_5C2333442C
#define JOBS_HEADER_GUARD_JOBSCUSTOMTABBARBUTTON_5C2333442C

#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

@interface JobsCustomTabBarButton : UIButton

@end

NS_ASSUME_NONNULL_END
#endif /* JOBS_HEADER_GUARD_JOBSCUSTOMTABBARBUTTON_5C2333442C */
