//
//  JobsBlockHeader.h
//  JobsBlock
//
//  Created by Jobs on 2026年6月8日，星期一.
//
//  统一维护 JobsBlock 内 Block typedef 使用到的向前声明，
//  避免 @class / @protocol 分散在多个业务头文件中。
//
#ifndef JobsBlockHeader_h
#define JobsBlockHeader_h
#pragma mark —— Class Forward Declarations
@class AFSecurityPolicy;
@class ASButtonNode;
@class ASCellNode;
@class ASCollectionNode;
@class ASDisplayNode;
@class ASEditableTextNode;
@class ASImageNode;
@class ASMapNode;
@class ASNetworkImageNode;
@class ASScrollNode;
@class ASStackLayoutSpec;
@class ASTableNode;
@class ASTextNode;
@class ASVideoNode;
@class AVAsset;
@class AVAudioMix;
@class BaseLabel;
@class BaseModel;
@class BaseNavigationBar;
@class BaseTableView;
@class BaseTextView;
@class BaseUploadFileRequest;
@class BaseView;
@class BRAddressPickerView;
@class BRDatePickerView;
@class BRPickerStyle;
@class BRStringPickerView;
@class BRStringPickerViewModel;
@class BRTextModel;
@class BRTextPickerView;
@class CAAnimation;
@class CABasicAnimation;
@class CADisplayLink;
@class CAEAGLLayer;
@class CAEmitterCell;
@class CAEmitterLayer;
@class CAGradientLayer;
@class CAKeyframeAnimation;
@class CALayer;
@class CAMediaTimingFunction;
@class CAMetalLayer;
@class CAPropertyAnimation;
@class CAReplicatorLayer;
@class CAScrollLayer;
@class CAShapeLayer;
@class CasinoCustomerContactElementModel;
@class CasinoCustomerContactModel;
@class CasinoGetiOSNewestVersionModel;
@class CATextLayer;
@class CATiledLayer;
@class CATransformLayer;
@class CAValueFunction;
@class CFGradientLabel;
@class CJTextField;
@protocol CJTextFieldDeleteDelegate;
@class CustomZFPlayerControlView;
@class FileFolderHandleModel;
@class FileNameModel;
@class FM_updatePassword_model;
@class FMAccModel;
@class FMBankDataModel;
@class FMBankDataSubModel;
@class FMBannerAdsModel;
@class FMDateModel;
@class FMDoorModel;
@class FMGameHomeSubMobileModel;
@class FMHomeMainBizSubView;
@class FMHotGameListModel;
@class FMInboxModel;
@class FMInboxTitleModel;
@class FMKYCInfoModel;
@class FMLikeModel;
@class FMMyBetOrderDetailModel;
@class FMMyGameBetOrderSumModel;
@class FMNameModel;
@class FMPagerModel;
@class FMReportTradeModel;
@class FMSubjectModel;
@class FMTableHeaderView1;
@class FMTypeModel;
@class FMWithDrawModel;
@class FSCalendar;
@class FSCalendarAppearance;
@class FSCalendarCell;
@class FSCalendarEventIndicator;
@class FSCalendarBlankCell;
@class FSCalendarCollectionView;
@class FSCalendarCollectionViewLayout;
@class FSCalendarCalculator;
@class FSCalendarDelegationProxy;
@class FSCalendarHeaderView;
@class FSCalendarHeaderCell;
@class FSCalendarHeaderLayout;
@class FSCalendarHeaderTouchDeliver;
@class FSCalendarStickyHeader;
@class FSCalendarTransitionCoordinator;
@class FSCalendarTransitionAttributes;
@class FSCalendarWeekdayView;
@protocol FSCalendarDelegate;
@protocol FSCalendarDataSource;
@protocol FSCalendarCollectionViewInternalDelegate;

@class GDFadeView;
@class GetDepositDiscountActivityRecordModel;
@class GKCustomNavigationBar;
@class GKGestureHandleConfigure;
@class GKNavigationBarConfigure;
@class GKPhoto;
@class GKPhotoBrowser;
@class GoodsClassModel;
@class GTC4Error;
@class GTCaptcha4Model;
@class GTCaptcha4ResultModel;
@class GTCaptcha4Session;
@class HQTextField;
@class HTMLDocument;
@class HXCollectionView;
@class HXCustomCameraViewController;
@class HXPhotoConfiguration;
@class HXPhotoManager;
@class HXPhotoModel;
@class HXPhotoPickerModel;
@class HXPhotoView;
@protocol HXPhotoViewCellCustomProtocol;
@protocol HXPhotoViewDelegate;
@class IncomeSourceModel;
@class IPApiModel;
@class IpifyModel;
@class IpinfoModel;
@class IQKeyboardManager;
@class JhtBannerCardView;
@class JhtBannerScrollView;
@class JobsAlertModel;
@class JobsAppDoorInputViewBaseStyle;
@class JobsAppDoorInputViewBaseStyleModel;
@class JobsAppDoorModel;
@class JobsBaseModel;
@class JobsBasePopupTextView;
@class JobsBtnStyleCVCell;
@class JobsChildCommentModel;
@class JobsCommentModel;
@class JobsControlTarget;
@class JobsCorModel;
@class JobsCountriesModel;
@class JobsCustomTabBar;
@class JobsCustomTabBarConfig;
@class JobsCustomTabBarVC;
@class JobsDecorationModel;
@class JobsExcelConfigureViewModel;
@class JobsExcelContentView;
@class JobsExcelLeftListView;
@class JobsExcelTopHeadView;
@class JobsExcelView;
@class JobsFileModel;
@class JobsFirstCommentCustomCofigModel;
@class JobsFirstCommentModel;
@class JobsGestureModel;
@class JobsHeaderFooterViewModel;
@class JobsHotLabelBySingleLine;
@class JobsImageModel;
@class JobsIMChatInfoModel;
@class JobsIMListDataModel;
@class JobsKeyValueModel;
@class JobsLocalNotificationModel;
@class JobsLocationModel;
@class JobsMagicTextField;
@class JobsMenuView;
@class JobsMsgDataModel;
@class JobsNavBar;
@class JobsNavBarConfig;
@class JobsNavigationTransitionMgr;
@class JobsNetworkSource;
@class JobsNetworkTrafficMonitor;
@class JobsOCKeyboardConfig;
@class JobsOCKeyboardMgr;
@class JobsOCKeyboardResult;
@class JobsParagraphStyleModel;
@class JobsResponseModel;
@class JobsRichTextConfig;
@class JobsRightBtnsView;
@class JobsSearchBar;
@class JobsSEL_IMP;
@class JobsStepView;
@class JobsTabBar;
@class JobsTabBarCtrl;
@class JobsTabBarItemConfig;
@class JobsTabBarVC;
@class JobsTextField;
@class JobsTextView;
@class JobsTimeModel;
@class JobsTimer;
@class JobsTimerMgr;
@class _JobsTimerMgrEntry;
@class JobsToggleBaseView;
@class JobsToggleNavView;
@class JobsTransitionAnimator;
@class JobsUserHeaderDataViewTBVCell;
@class JobsUserModel;
@class JobsViewNavigator;
@class JXCategoryBaseView;
@class JXCategoryDotView;
@class JXCategoryImageView;
@class JXCategoryIndicatorBackgroundView;
@class JXCategoryIndicatorLineView;
@class JXCategoryIndicatorView;
@class JXCategoryListContainerView;
@class JXCategoryNumberView;
@class JXCategoryTitleView;
@class KYCBaseView;
@class KYCModel;
@class LOTAnimationMJRefreshHeader;
@class LuckyWheelSegment;
@class LuckyWheelView;
@class LZTabBar;
@class LZTabBarConfig;
@class LZTabBarItem;
@class MASConstraint;
@class MASConstraintMaker;
@class MasonryModel;
@class MFMailComposeViewController;
@class MFMessageComposeViewController;
@class MGSwipeButtonModel;
@class MGSwipeTableCell;
@class MJRefreshAutoFooter;
@class MJRefreshAutoGifFooter;
@class MJRefreshAutoNormalFooter;
@class MJRefreshAutoStateFooter;
@class MJRefreshBackFooter;
@class MJRefreshBackGifFooter;
@class MJRefreshBackNormalFooter;
@class MJRefreshBackStateFooter;
@class MJRefreshConfigModel;
@class MJRefreshFooter;
@class MJRefreshGifHeader;
@class MJRefreshHeader;
@class MJRefreshNormalHeader;
@class MJRefreshStateHeader;
@class MSCommentDetailModel;
@class MSCommentModel;
@class NotificationModel;
@class NSCalendar;
@class NSDate;
@class NSDateFormatter;
@class NSLocale;
@class NSMutableParagraphStyle;
@class NSNotificationKeyboardModel;
@class NSTimeZone;
@class PDFDocument;
@class PDFView;
@class PhilippinesIDTypeModel;
@class PhilippinesModel;
@class PointLabBaseView;
@class PopListBaseView;
@class RACCommand;
@class RACCompoundDisposable;
@class RACReplaySubject;
@class RACScopedDisposable;
@class RACStream;
@class RACDisposable;
@class RACModel;
@class RACMulticastConnection;
@class RACScheduler;
@class RACSequence;
@class RACSignal;
@class RACSubject;
@class RACTuple;
@class RequestTool;
@class SDWebImageModel;
@class SlideToUnlockView;
@class SPAlertControllerConfig;
@class SRWebSocket;
@class SYSAlertControllerConfig;
@class SZTextView;
@class TDDrawingNode;
@class ThreeClassCell;
@class TMSCollectionViewLayout;
@class UIActivityIndicatorView;
@class UIBezierPath;
@class UIButtonModel;
@class UIGestureRecognizer;
@class UILongPressGestureRecognizer;
@class UIPanGestureRecognizer;
@class UIPinchGestureRecognizer;
@class UIRotationGestureRecognizer;
@class UIScreenEdgePanGestureRecognizer;
@class UISwipeGestureRecognizer;
@class UITapGestureRecognizer;
@class UITextFieldModel;
@class UITextModel;
@class UIViewModel;
@class UNNotificationRequestModel;
@class UNNotificationSound;
@class URLManagerModel;
@class UserDefaultModel;
@class VideoModel_Core;
@class WGradientProgressModel;
@class WMZBannerParam;
@class WMZBannerView;
@class XZMRefreshNormalHeader;
@class YTKBaseRequest;
@class YTKBatchRequest;
@class YTKChainRequest;
@class YTKNetworkConfig;
@class YTKRequest;
@class ZFPlayerController;
@class ZFAVPlayerManager;
@class ZFCustomControlView;
@class ZFDouYinControlView;
@class ZFIJKPlayerManager;
@class ZYTextField;
#pragma mark —— Protocol Forward Declarations
@protocol ASCollectionDataSource;
@protocol ASCollectionDelegate;
@protocol ASCollectionViewLayoutInspecting;
@protocol ASLayoutElement;
@protocol ASNetworkImageNodeDelegate;
@protocol CAAnimationDelegate;
@protocol JXCategoryIndicatorProtocol;
@protocol JXCategoryViewDelegate;
@protocol JXCategoryViewListContainer;
@protocol MFMailComposeViewControllerDelegate;
@protocol MFMessageComposeViewControllerDelegate;
@protocol MGSwipeTableCellDelegate;
@protocol MJRefreshProtocol;
@protocol PDFViewDelegate;
@protocol RACSubscriber;
@protocol TimerProtocol;
@protocol UIGestureRecognizerDelegate;
@protocol UIViewModelOthersProtocol;
@protocol YTKBatchRequestDelegate;
@protocol YTKChainRequestDelegate;
@protocol YTKRequestAccessory;
@protocol YTKRequestDelegate;
@protocol ZFPlayerMediaControl;
@protocol ZFPlayerMediaPlayback;
/// https://github.com/agiapp/BRPickerView
#ifndef BR_TEXT_PICKER_MODE_DEFINED
#define BR_TEXT_PICKER_MODE_DEFINED
/// 文本选择器类型
typedef NS_ENUM(NSInteger, BRTextPickerMode) {
    /** 单列选择器 */
    BRTextPickerComponentSingle,
    /** 多列选择器 */
    BRTextPickerComponentMulti,
    /** 多列联动选择器 */
    BRTextPickerComponentCascade
};
#endif
/// https://github.com/texturegroup/texture
#if __has_include(<AsyncDisplayKit/AsyncDisplayKit.h>)
#import <AsyncDisplayKit/AsyncDisplayKit.h>
#else
typedef struct {
    CGFloat leadingBufferScreenfuls;
    CGFloat trailingBufferScreenfuls;
} ASRangeTuningParameters;
#endif
/// https://github.com/yuantiku/YTKNetwork
#if __has_include(<YTKNetwork/YTKNetwork.h>)
#import <YTKNetwork/YTKNetwork.h>
#elif __has_include("YTKNetwork.h")
#import "YTKNetwork.h"
#endif
/// https://github.com/QuintGao/GKNavigationBar
#if __has_include(<GKNavigationBar/GKNavigationBar.h>)
#import <GKNavigationBar/GKNavigationBar.h>
#elif __has_include("GKNavigationBar.h")
#import "GKNavigationBar.h"
#endif

#if __has_include(<GKNavigationBar/GKGestureHandleConfigure.h>)
#import <GKNavigationBar/GKGestureHandleConfigure.h>
#elif __has_include("GKGestureHandleConfigure.h")
#import "GKGestureHandleConfigure.h"
#endif
/// https://github.com/renzifeng/ZFPlayer
#if __has_include(<ZFPlayer/ZFPlayer.h>)
#import <ZFPlayer/ZFPlayer.h>
#elif __has_include("ZFPlayer.h")
#import "ZFPlayer.h"
#endif

#if __has_include(<ZFPlayer/ZFAVPlayerManager.h>)
#import <ZFPlayer/ZFAVPlayerManager.h>
#elif __has_include("ZFAVPlayerManager.h")
#import "ZFAVPlayerManager.h"
#endif
#endif /* JobsBlockHeader_h */
