//
//  JobsBlockHeader.h
//  JobsBlock
//
//  Created by Jobs on 2026年6月8日，星期一.
//
//  统一维护 JobsBlock 内 Block typedef 使用到的向前声明，
//  避免 @class / @protocol 分散在多个业务头文件中。
//

#import <Foundation/Foundation.h>
#import <CoreMedia/CoreMedia.h>
#import <CoreText/CoreText.h>
#import <CommonCrypto/CommonCryptor.h>
#import <CommonCrypto/CommonHMAC.h>

#ifndef JobsBlockHeader_h
#define JobsBlockHeader_h

#pragma mark —— Jobs Enum Forward Declarations
typedef NS_ENUM(NSInteger, AppLanguage);
typedef NS_ENUM(NSInteger, BRTextPickerMode);
typedef NS_ENUM(NSUInteger, ComingStyle);
typedef NS_ENUM(NSInteger, ComponentType);
typedef NS_ENUM(NSInteger, DeviceOrientation);
typedef NS_ENUM(NSInteger, FMAccType);
typedef NS_ENUM(NSInteger, FMAdsType);
typedef NS_ENUM(NSInteger, FMJumpType);
typedef NS_ENUM(NSInteger, HTTPResponseCode);
typedef NS_ENUM(NSInteger, JobsCustomerContactStyle);
typedef NS_ENUM(NSInteger, JobsDirectionType);
typedef NS_ENUM(NSInteger, JobsDropDownListViewDirection);
typedef NS_ENUM(NSInteger, JobsHeaderFooterViewStyle);
typedef NS_ENUM(NSInteger, JobsImageRotationDirection);
typedef NS_ENUM(NSUInteger, JobsNetworkSourceType);
typedef NS_ENUM(NSUInteger, JobsOCKeyboardAccessoryPolicy);
typedef NS_ENUM(NSUInteger, JobsOCKeyboardApplyMode);
typedef NS_ENUM(NSUInteger, JobsOCSplashActionType);
typedef NS_ENUM(NSInteger, JobsOperationType);
typedef NS_ENUM(NSInteger, JobsInvokePolicy);
typedef NS_ENUM(NSUInteger, GKPhotoBrowserShowStyle);
typedef NS_ENUM(NSUInteger, GKPhotoBrowserHideStyle);
typedef NS_ENUM(NSInteger, JobsSwitchType);
typedef NS_ENUM(NSInteger, JobsSwitchType2);
typedef NS_ENUM(NSUInteger, JobsTimerState);
typedef NS_ENUM(NSUInteger, JobsTimerStyle);
typedef NS_ENUM(NSUInteger, JobsTimerType);
typedef NS_ENUM(NSUInteger, JobsTransitionDirection);
typedef NS_ENUM(NSInteger, JobsUpdateType);
typedef NS_ENUM(NSInteger, LoginType);
typedef NS_ENUM(NSUInteger, ShowTimeType);
typedef NS_ENUM(NSInteger, TimeZoneType);
typedef NS_ENUM(NSUInteger, UILabelShowingType);
typedef NS_OPTIONS(NSUInteger, JobsAppDoorGraphicCaptchaCharacterType);
typedef NS_ENUM(NSUInteger, TestLabelDemoControlType);
typedef NS_ENUM(NSInteger, NTESVerifyCodeLang);
typedef NS_ENUM(NSInteger, NTESVerifyCodeProtocol);
typedef NS_ENUM(NSInteger, NTESUserInterfaceStyle);
typedef NS_ENUM(NSUInteger, NTESCapBarTextAlign);
typedef NS_ENUM(NSUInteger, NSObject_SPAlertControllerInitType);
typedef NS_ENUM(NSInteger, VerificationStatus);
typedef NS_ENUM(NSInteger, PopupDirection);
typedef NS_ENUM(NSUInteger, LZTabBarItemType);
typedef NS_ENUM(NSInteger, ZFPlayerScalingMode);
typedef NS_ENUM(NSInteger, NEVPNIKEAuthenticationMethod);

#pragma mark —— Class Forward Declarations
@class AFSecurityPolicy;
@class ASButtonNode;
@class ASCellNode;
@class ASCollectionNode;
@class ASDisplayNode;
@class ASEditableTextNode;
@class ASImageNode;
@class ASMapNode;
@class ASNetworkImageNode;
@class ASScrollNode;
@class ASStackLayoutSpec;
@class ASTableNode;
@class ASTextNode;
@class ASVideoNode;
@class AVAsset;
@class AVAudioPlayer;
@class AVAudioRecorder;
@class AVAudioMix;
@class BaseLabel;
@class BaseModel;
@class BaseNavigationBar;
@class BaseTableViewHeaderFooterView;
@class BaseTableView;
@class BaseTextView;
@class NEVPNManager;
@class NEVPNProtocol;
@class NEVPNProtocolIKEv2;
@class BaseUploadFileRequest;
@class BaseView;
@class BRAddressPickerView;
@class BRDatePickerView;
@class BRPickerStyle;
@class BRStringPickerView;
@class BRStringPickerViewModel;
@class BRTextModel;
@class BRTextPickerView;
@class CAAnimation;
@class CABasicAnimation;
@class CADisplayLink;
@class CAEAGLLayer;
@class CAEmitterCell;
@class CAEmitterLayer;
@class CAGradientLayer;
@class CAKeyframeAnimation;
@class CALayer;
@class CAMediaTimingFunction;
@class CAMetalLayer;
@class CAPropertyAnimation;
@class CAReplicatorLayer;
@class CAScrollLayer;
@class CAShapeLayer;
@class CasinoCustomerContactElementModel;
@class CasinoCustomerContactModel;
@class CasinoGetiOSNewestVersionModel;
@class CATextLayer;
@class CATiledLayer;
@class CATransformLayer;
@class CAValueFunction;
@class CFGradientLabel;
@class CJTextField;
@protocol CJTextFieldDeleteDelegate;
@class CountdownView;
@class CustomZFPlayerControlView;
@class FileFolderHandleModel;
@class FileNameModel;
@class FM_updatePassword_model;
@class FMAccModel;
@class FMBankDataModel;
@class FMBankDataSubModel;
@class FMBannerAdsModel;
@class FMDateModel;
@class FMDoorModel;
@class FMGameHomeSubMobileModel;
@class FMHomeMainBizSubView;
@class FMHotGameListModel;
@class FMInboxModel;
@class FMInboxTitleModel;
@class FMKYCInfoModel;
@class FMLikeModel;
@class FMMyBetOrderDetailModel;
@class FMMyGameBetOrderSumModel;
@class FMNameModel;
@class FMPagerModel;
@class FMReportTradeModel;
@class FMSubjectModel;
@class FMTableHeaderView1;
@class FMTypeModel;
@class FMWithDrawModel;
@class FSCalendar;
@class FSCalendarAppearance;
@class FSCalendarCell;
@class FSCalendarEventIndicator;
@class FSCalendarBlankCell;
@class FSCalendarCollectionView;
@class FSCalendarCollectionViewLayout;
@class FSCalendarCalculator;
@class FSCalendarDelegationProxy;
@class FSCalendarHeaderView;
@class FSCalendarHeaderCell;
@class FSCalendarHeaderLayout;
@class FSCalendarHeaderTouchDeliver;
@class FSCalendarStickyHeader;
@class FSCalendarTransitionCoordinator;
@class FSCalendarTransitionAttributes;
@class FSCalendarWeekdayView;
@protocol FSCalendarDelegate;
@protocol FSCalendarDataSource;
@protocol FSCalendarCollectionViewInternalDelegate;

@class GDFadeView;
@class GetDepositDiscountActivityRecordModel;
@class GKCustomNavigationBar;
@class GKGestureHandleConfigure;
@class GKNavigationBarConfigure;
@class GKPhoto;
@class GKPhotoBrowser;
@class GKPhotoBrowserConfigure;
@protocol GKPhotoBrowserDelegate;
@class GoodsClassModel;
@class GTC4Error;
@class GTCaptcha4Model;
@class GTCaptcha4ResultModel;
@class GTCaptcha4Session;
@class HQTextField;
@class HTMLDocument;
@class HXCollectionView;
@class HXCustomCameraViewController;
@class HXPhotoConfiguration;
@class HXPhotoManager;
@class HXPhotoModel;
@class HXPhotoPickerModel;
@class HXPhotoView;
@protocol HXPhotoViewCellCustomProtocol;
@protocol HXPhotoViewDelegate;
@class IncomeSourceModel;
@class IPApiModel;
@class IpifyModel;
@class IpinfoModel;
@class IQKeyboardManager;
@class JhtBannerCardView;
@class JhtBannerScrollView;
@class JobsAlertModel;
@class JobsAppDoorInputViewBaseStyle;
@class JobsAppDoorGraphicCaptchaConfig;
@class JobsAppDoorContentView;
@class JobsAppDoorRegisterContentView;
@class JobsAppDoorInputViewBaseStyleModel;
@class JobsAppDoorModel;
@class JobsAppDoorConfig;
@class JobsAppDoorVC;
@class JobsAppDoorVC_Style2;
@class JobsAppTools;
@class JobsBaseModel;
@class JobsBasePopupTextView;
@class JobsBtnStyleCVCell;
@class JobsChildCommentModel;
@class JobsCommentModel;
@class JobsControlTarget;
@class JobsCorModel;
@class JobsCountriesModel;
@class JobsCustomTabBar;
@class JobsCustomTabBarConfig;
@class JobsCustomTabBarVC;
@class JobsDecorationModel;
@class JobsExcelConfigureViewModel;
@class JobsExcelContentView;
@class JobsExcelLeftListView;
@class JobsExcelTopHeadView;
@class JobsExcelView;
@class JobsFileModel;
@class JobsFirstCommentCustomCofigModel;
@class JobsFirstCommentModel;
@class JobsGestureModel;
@class JobsHeaderFooterViewModel;
@class JobsIconfontLoadResult;
@class JobsOCPatchModel;
@class JobsOCPatchRecord;
@class JobsHotLabelBySingleLine;
@class JobsImageModel;
@class JobsImageRotator;
@class JobsIMChatInfoModel;
@class JobsIMListDataModel;
@class JobsKeyValueModel;
@class JobsLocalNotificationModel;
@class JobsLocationModel;
@class JobsLinkageMenuView;
@class JobsMagicTextField;
@class JobsMarqueeView;
@class JobsMenuView;
@class JobsMsgDataModel;
@class JobsNavBar;
@class JobsNavBarConfig;
@class JobsNavBarWebVC;
@class JobsAnimationLabel;
@class JobsHeaderFooterView;
@class UICollectionHeaderFooterView;
@class JobsNavigationTransitionMgr;
@class JobsNetworkSource;
@class JobsNetworkTrafficMonitor;
@class JobsOCCalendar;
@class JobsOCWebSocketClient;
@class JobsGestureLockView;
@class JobsOCRootFoldTableCell;
@class JobsOCExcelView;
@class JobsOCRefreshConfig;
@class JobsOCGraphicCaptchaView;
@class ImageCodeView;
@class WeakTarget;
@class JobsOCKeyboardConfig;
@class JobsOCKeyboardMgr;
@class JobsOCKeyboardResult;
@class JobsParagraphStyleModel;
@class JobsPresentTransitionMgr;
@class JobsPullListAutoSizeView;
@class JobsResponseModel;
@class JobsRichTextConfig;
@class JobsRightMenuView;
@class JobsRightBtnsView;
@class JobsOCSearcherBar;
@class JobsSEL_IMP;
@class JobsSideDrawer;
@class JobsSideDrawerConfiguration;
@class JobsStepView;
@class JobsTabBar;
@class JobsTabBarCtrl;
@class JobsTabBarItem;
@class JobsTabBarItemConfig;
@class JobsTabBarVC;
@class JobsTextField;
@class JobsTextView;
@class JobsGestureLockConfiguration;
@class ZFSliderView;
@class JobsOCCommentModel;
@class JobsOCCommentView;
@class JobsOCRefreshConfig;
@class JobsTimeModel;
@class JobsTimer;
@class JobsTimerMgr;
@class JobsUploadingProgressView;
@class _JobsTimerMgrEntry;
@class JobsToggleBaseView;
@class JobsToggleNavView;
@class JobsTransitionAnimator;
@class JobsUserHeaderDataViewTBVCell;
@class JobsUserModel;
@class JobsViewNavigator;

@protocol JobsOCCalendarDataSource;
@protocol JobsOCCalendarDelegate;
@class JXCategoryBaseView;
@class JXCategoryDotView;
@class JXCategoryImageView;
@class JXCategoryIndicatorBackgroundView;
@class JXCategoryIndicatorLineView;
@class JXCategoryIndicatorView;
@class JXCategoryListContainerView;
@class JXCategoryNumberView;
@class JXCategoryTitleView;
@class KYCBaseView;
@class KYCModel;
@class LOTAnimationMJRefreshHeader;
@class LuckyWheelSegment;
@class LuckyWheelView;
@class LZTabBar;
@class LZTabBarConfig;
@class LZTabBarItem;
@class MASConstraint;
@class MASConstraintMaker;
@class MasonryModel;
@class MFMailComposeViewController;
@class MFMessageComposeViewController;
@class MGSwipeButtonModel;
@class MGSwipeTableCell;
@class MJRefreshAutoFooter;
@class MJRefreshAutoGifFooter;
@class MJRefreshAutoNormalFooter;
@class MJRefreshAutoStateFooter;
@class MJRefreshBackFooter;
@class MJRefreshBackGifFooter;
@class MJRefreshBackNormalFooter;
@class MJRefreshBackStateFooter;
@class MJRefreshConfigModel;
@class MJRefreshComponent;
@class MJRefreshFooter;
@class MJRefreshGifHeader;
@class MJRefreshHeader;
@class MJRefreshNormalHeader;
@class MJRefreshStateHeader;
@class MSCommentDetailModel;
@class MSCommentModel;
@class NotificationModel;
@class NSCalendar;
@class NSDate;
@class NSDateFormatter;
@class NSLocale;
@class NSMutableParagraphStyle;
@class NSNotificationKeyboardModel;
@class NSTimeZone;
@class PDFDocument;
@class PDFView;
@class PhilippinesIDTypeModel;
@class PhilippinesModel;
@class PointLabBaseView;
@class PopListBaseView;
@class RACCommand;
@class RACCompoundDisposable;
@class RACReplaySubject;
@class RACScopedDisposable;
@class RACStream;
@class RACDisposable;
@class RACModel;
@class RACMulticastConnection;
@class RACScheduler;
@class RACSequence;
@class RACSignal;
@class RACSubject;
@class RACTuple;
@class RequestTool;
@class SDWebImageModel;
@class SlideToUnlockView;
@class SPAlertControllerConfig;
@class SRWebSocket;
@class SYSAlertControllerConfig;
@class SZTextView;
@class TDDrawingNode;
@class ThreeClassCell;
@class TMSCollectionViewLayout;
@class UIActivityIndicatorView;
@class UIBezierPath;
@class UIButtonModel;
@class UIGestureRecognizer;
@class UILongPressGestureRecognizer;
@class UIPanGestureRecognizer;
@class UIPinchGestureRecognizer;
@class UIRotationGestureRecognizer;
@class UIScreenEdgePanGestureRecognizer;
@class UISwipeGestureRecognizer;
@class UITapGestureRecognizer;
@class UITextFieldModel;
@class UITextModel;
@class UILabelScrollingDemoVC;
@class TextCell;
@class ScrollDecelerator;
@class LuckyDiskDemoVC;
@class NotifiView;
@class JobsVideoTBVCell;
@class JobsIMListTBVCell;
@class JobsIMChatInfoTBVCell;
@class JXCategoryPopupVC;
@class JXCategoryPopupSubVC;
@class Douyin_ZFPlayerVC_1;
@class Douyin_ZFPlayerVC_2;
@class B_VC;
@class A_VC;
@class AppDelegate;
@class SceneDelegate;
@class SPAlertAction;
@class SPAlertController;
@class NTESVerifyCodeManager;
@class NTESVerifyCodeStyleConfig;
@class VideoModel_Core;
@class UIViewModel;
@class UNNotificationRequestModel;
@class UNNotificationSound;
@class URLManagerModel;
@class UserDefaultModel;
@class VideoModel_Core;
@class WGradientProgressModel;
@class WMZBannerParam;
@class WMZBannerView;
@class WMZBannerFadeLayout;
@class XZMRefreshNormalHeader;
@class YTKBaseRequest;
@class YTKBatchRequest;
@class YTKChainRequest;
@class YTKNetworkConfig;
@class YTKRequest;
@class ZFPlayerController;
@class ZFOrientationObserver;
@class TABAnimated;
@class ZFAVPlayerManager;
@class ZFCustomControlView;
@class ZFDouYinControlView;
@class ZFIJKPlayerManager;
@class ZYTextField;
#pragma mark —— Protocol Forward Declarations
@protocol SRWebSocketDelegate;
@protocol ASCollectionDataSource;
@protocol ASCollectionDelegate;
@protocol ASCollectionViewLayoutInspecting;
@protocol ASLayoutElement;
@protocol ASNetworkImageNodeDelegate;
@protocol CAAnimationDelegate;
@protocol JXCategoryIndicatorProtocol;
@protocol JXCategoryViewDelegate;
@protocol JXCategoryViewListContainer;
@protocol MFMailComposeViewControllerDelegate;
@protocol MFMessageComposeViewControllerDelegate;
@protocol MGSwipeTableCellDelegate;
@protocol MJRefreshProtocol;
@protocol PDFViewDelegate;
@protocol RACSubscriber;
@protocol TimerProtocol;
@protocol UIGestureRecognizerDelegate;
@protocol UIViewModelOthersProtocol;
@protocol YTKBatchRequestDelegate;
@protocol YTKChainRequestDelegate;
@protocol YTKRequestAccessory;
@protocol YTKRequestDelegate;
@protocol ZFPlayerMediaControl;
@protocol ZFPlayerMediaPlayback;
@protocol ZFSliderViewDelegate;
@protocol JobsOCVideoRecorderRecordButtonDelegate;
@protocol JobsOCVideoRecorderCaptureManagerDelegate;
@protocol LZTabBarItemDelegate;
@protocol LZTabBarDelegate;
/// https://github.com/agiapp/BRPickerView
#ifndef BR_TEXT_PICKER_MODE_DEFINED
#define BR_TEXT_PICKER_MODE_DEFINED
/// 文本选择器类型
typedef NS_ENUM(NSInteger, BRTextPickerMode) {
    /** 单列选择器 */
    BRTextPickerComponentSingle,
    /** 多列选择器 */
    BRTextPickerComponentMulti,
    /** 多列联动选择器 */
    BRTextPickerComponentCascade
};
#endif
/// https://github.com/texturegroup/texture

#if __has_include(<AsyncDisplayKit/AsyncDisplayKit.h>)
#import <AsyncDisplayKit/AsyncDisplayKit.h>
#else
typedef struct {
    CGFloat leadingBufferScreenfuls;
    CGFloat trailingBufferScreenfuls;
} ASRangeTuningParameters;
typedef struct {
    CGSize min;
    CGSize max;
} ASSizeRange;
#endif
/// https://github.com/yuantiku/YTKNetwork

#if __has_include(<YTKNetwork/YTKNetwork.h>)
#import <YTKNetwork/YTKNetwork.h>
#elif __has_include("YTKNetwork.h")
#import "YTKNetwork.h"
#endif
/// https://github.com/QuintGao/GKNavigationBar

#if __has_include(<GKNavigationBar/GKNavigationBar.h>)
#import <GKNavigationBar/GKNavigationBar.h>
#elif __has_include("GKNavigationBar.h")
#import "GKNavigationBar.h"
#endif

#if __has_include(<GKNavigationBar/GKGestureHandleConfigure.h>)
#import <GKNavigationBar/GKGestureHandleConfigure.h>
#elif __has_include("GKGestureHandleConfigure.h")
#import "GKGestureHandleConfigure.h"
#endif
/// https://github.com/renzifeng/ZFPlayer

#if __has_include(<ZFPlayer/ZFPlayer.h>)
#import <ZFPlayer/ZFPlayer.h>
#elif __has_include("ZFPlayer.h")
#import "ZFPlayer.h"
#endif

#if __has_include(<ZFPlayer/ZFAVPlayerManager.h>)
#import <ZFPlayer/ZFAVPlayerManager.h>
#elif __has_include("ZFAVPlayerManager.h")
#import "ZFAVPlayerManager.h"
#endif
// JOBS_PROPERTY_DSL_FORWARD_AUTOGEN_BEGIN
@class AFSecurityPolicy;
@class ASButtonNode;
@class ASEditableTextNode;
@class ASLayoutElementStyle;
@class ASMapNode;
@class ASNetworkImageNode;
@class ASTableNode;
@class ASVideoNode;
@class AVAssetImageGenerator;
@class AVAssetWriterInput;
@class AVAudioRecorder;
@class AVCaptureAudioDataOutput;
@class AVCaptureConnection;
@class AVCaptureDeviceInput;
@class AVCaptureSession;
@class AVCaptureVideoDataOutput;
@class AVCaptureVideoPreviewLayer;
@class AVPlayerLayer;
@class AppDelegate;
@class BRDatePickerView;
@class BRPickerStyle;
@class BaiShaETProjCollectionHeaderView;
@class BaiShaETProjPopupView10;
@class BaseButton;
@class BaseContentView;
@class BaseNavigationBar;
@class BaseViewController;
@class CAAnimation;
@class CAAnimationGroup;
@class CADisplayLink;
@class CAGradientLayer;
@class CAKeyframeAnimation;
@class CALayer;
@class CAShapeLayer;
@class CBPeripheral;
@class CBUUID;
@class CasinoCustomerServiceView;
@class CasinoUpgradeContentView;
@class CompressStrVC;
@class CoreDataVC;
@class CustomZFPlayerControlView;
@class FMGameCVCell;
@class FMHomeMainBizSubView;
@class GXCardViewDemoVC;
@class GifLoopPlayView;
@class GoodsClassModel;
@class HAHandleDemoView;
@class HXPhotoModel;
@class HotRefreshVC;
@class JXCategoryIndicatorLineView;
@class JXCategoryPopupVC;
@class JXCategoryTimelineCellModel;
@class JXCategoryTitleBackgroundCell;
@class JXCategoryTitleBackgroundCellModel;
@class JXCategoryTitleBackgroundView;
@class JXPagerView;
@class JobsAnimatedNumberLabelDemoVC;
@class JobsAnimationLabel;
@class JobsAppDoorConfig;
@class JobsAppDoorContentView;
@class JobsAppDoorGraphicCaptchaConfig;
@class JobsAppDoorInputViewBaseStyleModel;
@class JobsAppDoorInputViewBaseStyle_10;
@class JobsAppDoorInputViewBaseStyle_1;
@class JobsAppDoorInputViewBaseStyle_2;
@class JobsAppDoorInputViewBaseStyle_3;
@class JobsAppDoorInputViewBaseStyle_4;
@class JobsAppDoorInputViewBaseStyle_5;
@class JobsAppDoorInputViewBaseStyle_6;
@class JobsAppDoorInputViewBaseStyle_7;
@class JobsAppDoorInputViewBaseStyle_8;
@class JobsAppDoorInputViewBaseStyle_9;
@class JobsAppDoorInputViewTFModel;
@class JobsAppDoorLoginContentView;
@class JobsAppDoorModel;
@class JobsAppDoorRegisterConfig;
@class JobsAppDoorRegisterContentView;
@class JobsAppDoorVC;
@class JobsAppDoorVC_Style2;
@class JobsBaseApi;
@class JobsBaseDataSettingVC;
@class JobsBaseTableViewCell;
@class JobsBluetoothManager;
@class JobsBluetoothProfile;
@class JobsChildCommentModel;
@class JobsClockIconView;
@class JobsClockView;
@class JobsCollectionViewDataSourceMux;
@class JobsCollectionViewDelegateMux;
@class JobsCommentCoreVC;
@class JobsCommentModel;
@class JobsCommentPopUpView_viewForHeaderInSection;
@class JobsCoreTextScrollLayer;
@class JobsCountdownLayerDemoVC;
@class JobsCountdownView;
@class JobsCustomTabBarConfig;
@class JobsCustomTabBarVC;
@class JobsCustomView;
@class JobsDouyinRefreshView;
@class JobsDropDownListVC;
@class JobsDropDownListView;
@class JobsExcelConfigureViewModel;
@class JobsExcelContentView;
@class JobsExcelLeftListView;
@class JobsExcelTopHeadView;
@class JobsFirstCommentCustomCofigModel;
@class JobsFirstCommentModel;
@class JobsGIFRefreshView;
@class JobsGestureLockVC;
@class JobsGestureLockView;
@class JobsGetiOSNewestVersionModel;
@class JobsHandwritingCanvasView;
@class JobsHandwritingDemoVC;
@class JobsHotLabelByMultiLine;
@class JobsHotLabelBySingleLine;
@class JobsHotLabelWithMultiLineModel;
@class JobsIMChatInfoModel;
@class JobsIMVC;
@class JobsIconfontCacheDemoVC;
@class JobsIconfontLoadToken;
@class JobsImageNumberView;
@class JobsImageRefreshView;
@class JobsImageRotator;
@class JobsLabelScrollController;
@class JobsLinkageMenuView;
@class JobsLinkageMenuViewConfig;
@class JobsLinkageMenuViewDemoVC;
@class JobsLiveStreamDemoVC;
@class JobsLottieRefreshView;
@class JobsMarqueeView;
@class JobsMonitorNetwoking;
@class JobsMosaicBaseDemoVC;
@class JobsMosaicBrushDemoVC;
@class JobsMosaicBrushImageView;
@class JobsMosaicWholeImageDemoVC;
@class JobsMsgDataModel;
@class JobsMsgDetailVC;
@class JobsMultiTimerTableDemoVC;
@class JobsNavBar;
@class JobsNavBarConfig;
@class JobsNavSettingVC;
@class JobsNavigationDemoVC;
@class JobsOCAudioPlayerEngine;
@class JobsOCAudioRecordButton;
@class JobsOCAudioRecorderDemoVC;
@class JobsOCAudioRecorderEngine;
@class JobsOCAudioRecording;
@class JobsOCBaseConfigDemoUITests;
@class JobsOCBaseConfigDemoUITestsLaunchTests;
@class JobsOCCalendar;
@class JobsOCCalendarAppearance;
@class JobsOCCalendarDayCell;
@class JobsOCCommentModeDetailVC;
@class JobsOCCommentModel;
@class JobsOCCrashLogCenter;
@class JobsOCCrashLogMemorySnapshot;
@class JobsOCDSLAnimatedNumberStore;
@class JobsOCDemoListSettingsVC;
@class JobsOCExcelCell;
@class JobsOCExcelColumn;
@class JobsOCExcelDemoVC;
@class JobsOCExcelRow;
@class JobsOCExcelStyle;
@class JobsOCExcelView;
@class JobsOCGraphicCaptchaConfig;
@class JobsOCGraphicCaptchaDemoVC;
@class JobsOCKeyboardConfig;
@class JobsOCKeyboardMgr;
@class JobsOCKeyboardResult;
@class JobsOCMarkdownConfiguration;
@class JobsOCMarkdownDocument;
@class JobsOCMarkdownDocumentsDemoVC;
@class JobsOCMarkdownView;
@class JobsOCRefreshComponent;
@class JobsOCRefreshProxy;
@class JobsOCRefreshSlot;
@class JobsOCRefresherDemoVC;
@class JobsOCRootFoldTableCell;
@class JobsOCSceneDelegateDemoVC;
@class JobsOCSearcherBar;
@class JobsOCSearcherRecordCell;
@class JobsOCSearcherView;
@class JobsOCSkeletonConfig;
@class JobsOCSkeletonUser;
@class JobsOCSkeletonViewDemoVC;
@class JobsOCSnowflake;
@class JobsOCSplashConfiguration;
@class JobsOCSplashVC;
@class JobsOCVideoRecorderAssetWriter;
@class JobsOCVideoRecorderCIFilterProcessor;
@class JobsOCVideoRecorderCaptureManager;
@class JobsOCVideoRecorderConfig;
@class JobsOCWebSocketClient;
@class JobsPlayerTBVCell;
@class JobsPopUpVC;
@class JobsPostDelView;
@class JobsPostVC;
@class JobsPresentTransitionMgr;
@class JobsPresentationCtrl;
@class JobsProgressBar;
@class JobsProgressDemoVC;
@class JobsQRCodeDemoVC;
@class JobsRedPacketRainConfig;
@class JobsRedPacketRainDemoVC;
@class JobsRedPacketRainView;
@class JobsRichTextConfig;
@class JobsRightMenuView;
@class JobsScale;
@class JobsScreenshotObserver;
@class JobsScreenshotProtectionView;
@class JobsScrollYView;
@class JobsSettingGestureVC;
@class JobsShakeBtn;
@class JobsShootingVC;
@class JobsSideDrawer;
@class JobsSideDrawerDemoVC;
@class JobsSphereDemoVC;
@class JobsStepView;
@class JobsSuspendView;
@class JobsSwiftParityControlEventsDemoVC;
@class JobsSwiftParityMomentsPreviewDemoVC;
@class JobsSysProgressDemoVC;
@class JobsTabBar;
@class JobsTabBarCtrl;
@class JobsTabBarVC;
@class JobsTableViewDataSourceMux;
@class JobsTableViewDelegateMux;
@class JobsTextField;
@class JobsThemeCenter;
@class JobsTimer;
@class JobsTimerTargetProxy;
@class JobsTimerVC;
@class JobsTodayNewsRefreshView;
@class JobsToggleBaseView;
@class JobsToggleNavView;
@class JobsUploadingProgressView;
@class JobsUserModel;
@class JobsVerticalMenuSubVC;
@class JobsVerticalMenuSubView;
@class JobsVerticalMenuVC_0;
@class JobsVerticalMenuVC_1;
@class JobsVerticalMenuVC_2;
@class JobsViewNavigator;
@class JobsViewPushPresentation;
@class JobsViewPushTransitionView;
@class JobsWalletCardCollectionViewCell;
@class JobsWalletCardModel;
@class JobsWalletCardView;
@class JobsWalletCollectionViewLayout;
@class JobsWalletVC;
@class LAContext;
@class LOTAnimationView;
@class LZTabBarController;
@class LiveChat;
@class LuckyDiskDemoVC;
@class LuckyWheelView;
@class MASConstraint;
@class MSCommentDetailModel;
@class MSCommentModel;
@class MasonryModel;
@class MyProxy;
@class NSArray;
@class NSAttributedString;
@class NSBundle;
@class NSCalendar;
@class NSData;
@class NSDate;
@class NSDictionary;
@class NSError;
@class NSIndexPath;
@class NSLocale;
@class NSManagedObjectContext;
@class NSMutableArray;
@class NSMutableIndexSet;
@class NSMutableURLRequest;
@class NSNumber;
@class NSObject;
@class NSPointerArray;
@class NSPredicate;
@class NSShadow;
@class NSSortDescriptor;
@class NSString;
@class NSTimer;
@class NSURL;
@class NSURLSessionConfiguration;
@class NSUserActivity;
@class NSValue;
@class OCDynamicRegisterVC;
@class PHAssetCreationRequest;
@class PHCycleView;
@class PHFetchOptions;
@class PHImageRequestOptions;
@class PHVideoRequestOptions;
@class PicToStrStoreSubVC;
@class PopListBaseView;
@class PreviewVC;
@class RACCompoundDisposable;
@class RACDisposable;
@class RACGestureRecognizerActionHandler;
@class RACSubject;
@class RBCLikeButton;
@class RYCuteView;
@class Reachability;
@class Realm_VC;
@class RequestTool;
@class SRWebSocket;
@class SlideToUnlockView;
@class TMSCollectionViewLayout;
@class TestLabelDemoModel;
@class TestLabelDetailVC;
@class TextureDemoVC;
@class ThreeClassCell;
@class TransitionController;
@class UIApplication;
@class UIBarButtonItem;
@class UIButton;
@class UIButtonModel;
@class UICollectionViewLayoutAttributes;
@class UIColor;
@class UIFont;
@class UIGestureRecognizer;
@class UIImage;
@class UILabel;
@class UILabelScrollingDemoVC;
@class UINavigationController;
@class UINavigationItem;
@class UIPanGestureRecognizer;
@class UIPopoverPresentationController;
@class UISceneConfiguration;
@class UISceneSessionActivationRequest;
@class UIScrollView;
@class UITabBar;
@class UITabBarItem;
@class UITableViewCell;
@class UITapGestureRecognizer;
@class UIView;
@class UIViewController;
@class UIViewModel;
@class UIWindowScene;
@class VideoModel_Core;
@class WKFindConfiguration;
@class WeakTarget;
@class WidgetVC;
@class XCTAttachment;
@class XDTextBtnView;
@class XLBubbleTransition;
@class YTKNetworkConfig;
@class ZFAVPlayerManager;
@class ZFCustomControlView;
@class ZFIJKPlayerManager;
@class ZFPlayerController;
@class ZFSpeedLoadingView;
@class _FDFullscreenPopGestureRecognizerDelegate;
@class _JobsFuseBubbleRunner;
@protocol ASTableDataSource;
@protocol ASTableDelegate;
@protocol JobsMosaicBrushImageViewDelegate;
@protocol JobsOCVideoRecorderFilterProtocol;
@protocol JobsRefreshAnimatorProtocol;
@protocol NSObject;
@protocol TFPopupDelegate;
@protocol UICollectionViewDataSource;
@protocol UICollectionViewDelegate;
@protocol UITableViewDataSource;
@protocol UITableViewDelegate;
@protocol UIViewControllerContextTransitioning;
@protocol UIViewControllerTransitioningDelegate;
@protocol ZFPlayerMediaPlayback;
typedef NSString *AVLayerVideoGravity NS_STRING_ENUM;
typedef NSString *JobsThemeStyle NS_TYPED_EXTENSIBLE_ENUM;
typedef NS_ENUM(NSInteger, AVCaptureVideoOrientation);
typedef NS_ENUM(NSInteger, AlignmentType);
typedef NS_ENUM(NSInteger, JobsAppDoorBgType);
typedef NS_ENUM(NSInteger, JobsWidgetDemoFamily);
typedef NS_ENUM(NSInteger, PHImageRequestOptionsDeliveryMode);
typedef NS_ENUM(NSInteger, PHVideoRequestOptionsDeliveryMode);
typedef NS_ENUM(NSInteger, PHVideoRequestOptionsVersion);
typedef NS_ENUM(NSInteger, UIModalPresentationStyle);
typedef NS_ENUM(NSInteger, UINavigationItemLargeTitleDisplayMode);
typedef NS_ENUM(NSInteger, XCTAttachmentLifetime);
typedef NS_ENUM(NSUInteger, JobsOCMarkdownAppearance);
typedef NS_ENUM(NSUInteger, JobsSettingGestureFlowState);
typedef NS_ENUM(NSUInteger, JobsSysProgressDemoMode);
typedef NS_ENUM(NSUInteger, MASAxisType);
typedef NS_ENUM(NSUInteger, SourceType);
typedef NS_ENUM(NSUInteger, ZFPlayerPlaybackState);
typedef NS_OPTIONS(NSUInteger, UIPopoverArrowDirection);
typedef NS_OPTIONS(NSUInteger, ZFPlayerLoadState);
// JOBS_PROPERTY_DSL_FORWARD_AUTOGEN_END

// JOBS_INLINE_BLOCK_FORWARD_AUTOGEN_BEGIN
@class JobsBluetoothCommand;
@class JobsBluetoothManager;
@class JobsBluetoothMockTransport;
@class JobsBluetoothPeripheral;
@class JobsBluetoothProfile;
@class JobsDouyinRefreshConfig;
@class JobsFuseBubbleConfig;
@class JobsFuseOuterRingConfig;
@class JobsOCCommentModel;
@class JobsOCCommentView;
@class JobsOCOpenConfiguration;
@class JobsOCSearcherView;
@class JobsOCSplashAction;
@class JobsOCSplashConfiguration;
@class JobsProgressBar;
@class JobsTodayNewsRefreshConfig;
@class NSArray;
@class NSData;
@class NSError;
@class NSNumber;
@class NSString;
@class NSURL;
@class SlideToUnlockView;
@class UIButtonConfiguration;
@class UIButtonModel;
@class UIColor;
@class UIImage;
typedef NS_ENUM(NSInteger, JobsBluetoothState);
typedef NS_ENUM(NSInteger, JobsOCCommentMode);
typedef NS_ENUM(NSUInteger, JobsOCOpenMode);
typedef NS_ENUM(NSUInteger, JobsProgressBarDirection);
typedef NS_ENUM(NSUInteger, JobsProgressBarLabelPlacement);
typedef NS_ENUM(NSUInteger, JobsProgressBarValueMode);
// JOBS_INLINE_BLOCK_FORWARD_AUTOGEN_END

// JOBS_FUNCTIONAL_BLOCK_FORWARD_AUTOGEN_BEGIN

#pragma mark —— Generated Functional Block Forward Declarations
@class ASLayoutSpec;
@class ASTableNode;
@class AVCaptureDevice;
@class BaseButton;
@class CABasicAnimation;
@class CADisplayLink;
@class CAGradientLayer;
@class CAKeyframeAnimation;
@class CAMediaTimingFunction;
@class CAShapeLayer;
@class CBCentralManager;
@class CIFilter;
@class CIImage;
@class FMDatabase;
@class FMDoorModel;
@class FMResultSet;
@class FSCalendar;
@class GKGestureHandleConfigure;
@class GKNavigationBarConfigure;
@class GTCaptcha4Session;
@class GXCardView;
@class GXCardViewCell;
@class HXPhotoModel;
@class HXPhotoView;
@class IPApiModel;
@class IpifyModel;
@class IpinfoModel;
@class JXCategoryBaseCellModel;
@class JXCategoryListContainerView;
@class JXCategoryPopupSubVC;
@class JXPagerView;
@class JobsAppDoorInputViewBaseStyle;
@class JobsBaseTableViewCell;
@class JobsClockIconView;
@class JobsCommentTitleHeaderView;
@class JobsDouyinRefreshConfig;
@class JobsDropDownListView;
@class JPImageresizerAppearance;
@class JobsFuseBubbleConfig;
@class JobsFuseOuterRingConfig;
@class JobsGraphicCaptchaConfig;
@class JobsIMListDataModel;
@class JobsImageModel;
@class JobsLabelScrollConfiguration;
@class JobsLabelScrollController;
@class JobsLocalNotificationModel;
@class JobsMagicTextField;
@class JobsMonitorNetwoking;
@class JobsMsgDataModel;
@class JobsNavBar;
@class JobsNavBarConfig;
@class JobsNoticePopupView;
@class JobsOCAudioRecorderEngine;
@class JobsOCAudioRecording;
@class JobsOCCalendar;
@class JobsOCCalendarAppearance;
@class JobsOCCalendarDayCell;
@class JobsOCCommentConfig;
@class JobsOCExcelCellContext;
@class JobsOCExcelCell;
@class JobsOCExcelColumn;
@class JobsOCCommentModel;
@class JobsOCCommentView;
@class JobsOCCountryCodeCtrl;
@class JobsOCCrashLogFileInfo;
@class JobsOCCrashLogMemorySnapshot;
@class JobsOCDSLAnimatedNumberStore;
@class JobsOCDemoSectionModel;
@class JobsOCExcelCell;
@class JobsOCGraphicCaptchaConfig;
@class JobsOCKeyboardConfig;
@class JobsOCMarkdownConfiguration;
@class JobsOCMarkdownDocument;
@class JobsOCMarkdownCatalog;
@class JobsOCMarkdownDocumentDemoVC;
@class JobsOCMarkdownDocumentsDemoVC;
@class JobsOCMarkdownView;
@class JobsOCOpenConfiguration;
@class JobsOCOpenWebViewController;
@class JobsPageView;
@class JobsOCNumberStepper;
@class JobsOCPatchModel;
@class JobsOCRefreshProxy;
@class JobsOCRefreshSlot;
@class JobsOCSceneDelegateDemoVC;
@class JobsOCSearcherConfig;
@class JobsOCSearcherView;
@class JobsOCSkeletonConfig;
@class JobsOCSkeletonUser;
@class JobsOCSplashAction;
@class JobsOCVideoRecorderResult;
@class JobsOCVideoRecorderCaptureManager;
@class JobsOCSplashConfiguration;
@class JobsOCSplashVC;
@class JobsOCVideoRecorderRecordButton;
@class JobsOCVideoRecorderPreviewView;
@class JobsOCVideoRecorderAssetWriter;
@class JobsOCVideoRecorderVC;
@class JobsPresentTransitionMgr;
@class JobsRedPacketRainConfig;
@class JobsRedPacketRainView;
@class JobsResponseModel;
@class JobsRichTextConfig;
@class JobsSystemRefreshView;
@class JobsTabBar;
@class JobsTabBarCtrl;
@class JobsTimeModel;
@class JobsTodayNewsRefreshConfig;
@class JobsUserModel;
@class JobsViewPushPresentation;
@class JobsWalletCardModel;
@class JobsGIFRefreshView;
@class JobsOCAudioRecordButton;
@class ZBURLRequest;
@class BaseViewController;
@class JXCategoryViewVerticalShowSubBaseVC;
@class JobsYTKChainDelegateProxy;
@class LMHWaterFallLayout;
@class LOTAnimationView;
@class LZTabBarConfig;
@class LiveChatMessage;
@class LoginView;
@class LuckyWheelSegment;
@class MASConstraintMaker;
@class MGSwipeTableCell;
@class MJRefreshConfigModel;
@class MsgEditBoardView;
@class NSArray;
@class NSAttributedString;
@class NSBundle;
@class NSCharacterSet;
@class NSCoder;
@class NSData;
@class NSDate;
@class NSDictionary;
@class NSError;
@class NSIndexPath;
@class NSIndexSet;
@class NSInvocation;
@class NSLocale;
@class NSManagedObject;
@class NSMethodSignature;
@class NSMutableArray;
@class NSMutableAttributedString;
@class NSMutableParagraphStyle;
@class NSMutableSet;
@class NSMutableString;
@class NSMutableURLRequest;
@class NSNumber;
@class NSPointerArray;
@class NSString;
@class NSTimer;
@class NSURL;
@class NSUUID;
@class NSUserActivity;
@class NSValue;
@class NotifiView;
@class PHAssetCollection;
@class Protocol;
@class PwdSettingByCodeView;
@class PwdSettingView;
@class Reachability;
@class SDWebImageModel;
@class SRWebSocket;
@class SZTextView;
@class SignUpView;
@class SocketRocketUtility;
@class SpreadsheetView;
@class TBCityIconInfo;
@class TFPopupParam;
@class TestLabelDemoModel;
@class UIApplication;
@class UIBarButtonItem;
@class UIBezierPath;
@class UIButton;
@class UIButtonConfiguration;
@class UIButtonModel;
@class UICollectionView;
@class UICollectionViewLayoutAttributes;
@class UIColor;
@class UIControl;
@class UIDevice;
@class UIFont;
@class UIGestureRecognizer;
@class UIImage;
@class UINavigationController;
@class UIPanGestureRecognizer;
@class UIScene;
@class UISceneSession;
@class UIScrollView;
@class UISearchController;
@class UITabBar;
@class UITableView;
@class UITableViewCell;
@class UITextField;
@class UITextView;
@class UITouch;
@class UITraitCollection;
@class UIView;
@class UIViewController;
@class UIViewModel;
@class UIWindowScene;
@class UNMutableNotificationContent;
@class UNNotificationAttachment;
@class UNUserNotificationCenter;
@class User_Realm;
@class XLChannelControl;
@class XLChannelHeader;
@class XLChannelView;
@class YTKAnimatingRequestAccessory;
@class YTKBatchRequest;
@class YTKChainRequest;
@class YTKUrlArgumentsFilter;
@class ZFAVPlayerManager;
@class ZFDouYinControlView;
@class ZFIJKPlayerManager;
@class ZFPlayerController;
@class ZFPlayerGestureControl;
@class ZMJCellRange;
@class ZMJTask;
@class ZMJTipView;
@class ZYTextField;
@class _ASDisplayLayer;
@class _FDFullscreenPopGestureRecognizerDelegate;
@class _JobsOnceState;
@class AVPlayer;
@protocol FlutterPluginRegistrar;
@protocol JobsRefreshAnimatorProtocol;
@protocol NSObject;
@protocol UIContentContainer;
@protocol UIViewControllerAnimatedTransitioning;
@protocol UIViewControllerContextTransitioning;
typedef NS_ENUM(NSInteger, AppLanguage);
typedef NS_ENUM(NSInteger, GXCardCellSwipeDirection);
typedef NS_ENUM(NSInteger, HTTPRequestHeaderLanguageType);
typedef NS_ENUM(NSInteger, IQAutoToolbarManageBehavior);
typedef NS_ENUM(NSInteger, JobsIconfontGlyph);
typedef NS_ENUM(NSInteger, JobsOCCalendarMonthPosition);
typedef NS_ENUM(NSInteger, JobsOCCalendarScope);
typedef NS_ENUM(NSUInteger, JobsOCCalendarPlaceholderType);
typedef NS_OPTIONS(NSUInteger, JobsOCCalendarCaseOptions);
typedef NS_ENUM(NSInteger, JobsOCCommentMode);
typedef NS_ENUM(NSInteger, JobsOCDemoListCellTextDisplayStrategy);
typedef NS_ENUM(NSInteger, JobsOCDemoListSettingSection);
typedef NS_ENUM(NSInteger, JobsOCSkeletonAnimationStyle);
typedef NS_ENUM(NSInteger, JobsOCWebSocketState);
typedef NS_ENUM(NSInteger, JobsSideDrawerContentMode);
typedef NS_ENUM(NSInteger, JobsSideDrawerDirection);
typedef NS_ENUM(NSInteger, JobsViewPushDirection);
typedef NS_ENUM(NSInteger, JobsWalletCardExpandStyle);
typedef NS_ENUM(NSInteger, MJRefreshState);
typedef NS_ENUM(NSInteger, ScrollDirection);
typedef NS_ENUM(NSInteger, UIDeviceOrientation);
typedef NS_ENUM(NSInteger, UIInterfaceOrientation);
typedef NS_ENUM(NSInteger, YTKRequestMethod);
typedef NS_ENUM(NSInteger, YTKRequestSerializerType);
typedef NS_ENUM(NSInteger, ZMJTimeUnit);
typedef NS_ENUM(NSUInteger, JobsBioKitResult);
typedef NS_ENUM(NSUInteger, JobsBioKitType);
typedef NS_ENUM(NSUInteger, JobsGestureLockValidationResult);
typedef NS_ENUM(NSUInteger, JobsLabelTextDisplayMode);
typedef NS_ENUM(NSUInteger, JobsMarqueeDirection);
typedef NS_ENUM(NSUInteger, JobsMarqueeScrollMode);
typedef NS_ENUM(NSUInteger, JobsMarqueeItemSizeMode);
typedef NS_ENUM(NSUInteger, JobsMarqueePageControlPosition);
typedef NS_ENUM(NSUInteger, JobsOCAudioRecordingMode);
typedef NS_ENUM(NSUInteger, JobsOCOpenResult);
typedef NS_ENUM(NSUInteger, JobsOCRefreshHorizontalMode);
typedef NS_ENUM(NSUInteger, JobsOCRefreshPosition);
typedef NS_ENUM(NSUInteger, JobsOCRefreshRole);
typedef NS_ENUM(NSUInteger, JobsOCRefreshState);
typedef NS_ENUM(NSUInteger, JobsOCSplashContentType);
typedef NS_ENUM(NSUInteger, JobsOCVideoRecorderCIFilterType);
typedef NS_ENUM(NSUInteger, JobsRefreshAnimatorPhase);
typedef NS_ENUM(NSUInteger, JobsTimerType);
typedef NS_OPTIONS(NSUInteger, JobsGraphicCaptchaCharacterUnit);
typedef NS_OPTIONS(NSUInteger, JobsOCGraphicCaptchaCharacterUnit);
typedef NS_OPTIONS(NSUInteger, SDWebImageOptions);
typedef NS_OPTIONS(NSUInteger, UIInterfaceOrientationMask);

#pragma mark —— Generated Functional Value Alias Declarations
typedef NSString * JobsIconfontRemoteAsset NS_TYPED_ENUM;
#ifndef JOBS_INDEX_PATH_STRUCT_DEFINED
#define JOBS_INDEX_PATH_STRUCT_DEFINED
typedef struct {
    NSInteger section;
    NSInteger rowOrItem;
} JobsIndexPath;
#endif

#pragma mark —— Generated Functional Block Alias Declarations
typedef void(^FetchNotifiViewBlock)(NotifiView *_Nullable view);
typedef void(^JobsMarqueePageControlConstraintsBlock)(MASConstraintMaker *make);
typedef void(^JobsOCRefreshActionBlock)(void);
typedef void(^JobsOCSplashActionBlock)(__kindof JobsOCSplashVC *_Nullable splashVC);
typedef void(^JobsOCVideoRecorderWriterFinishBlock)(NSURL *_Nullable fileURL,
                                                    CMTime duration,
                                                    NSError *_Nullable error);
typedef BOOL(^JobsRetBOOLByBOOLBlock)(BOOL data);
typedef BOOL(^JobsRetBOOLByIDBlock)(id _Nullable data);
typedef BOOL(^JobsRetBOOLByNSUIntegerBlock)(NSUInteger data);
typedef char(^JobsRetByCharBlock)(char data);
typedef double(^JobsRetByDoubleBlock)(double data);
typedef float(^JobsRetByFloatBlock)(float data);
typedef long(^JobsRetByLongBlock)(long data);
typedef NSInteger(^JobsRetByNSIntegerBlock)(NSInteger data);
typedef NSUInteger(^JobsRetByNSUIntegerBlock)(NSUInteger data);
typedef short(^JobsRetByShortBlock)(short data);
typedef unsigned char(^JobsRetByUnsignedCharBlock)(unsigned char data);
typedef unsigned int(^JobsRetByUnsignedIntBlock)(unsigned int data);
typedef unsigned long(^JobsRetByUnsignedLongBlock)(unsigned long data);
typedef unsigned long long(^JobsRetByUnsignedLongLongBlock)(unsigned long long data);
typedef unsigned short(^JobsRetByUnsignedShortBlock)(unsigned short data);
typedef CGFloat(^JobsRetCGFloatByCGFloatBlock)(CGFloat data);
typedef CGFloat(^JobsRetCGFloatByIDBlock)(id _Nullable data);
typedef char(^JobsRetCharByIDBlock)(id _Nullable data);
typedef double(^JobsRetDoubleByIDBlock)(id _Nullable data);
typedef float(^JobsRetFloatByIDBlock)(id _Nullable data);
typedef id _Nullable(^JobsRetIDByComponentTypeAndUIViewBlock)(Jobs_ReturnIDByComponentTypeAndUIViewBlock_Arguments);
typedef id _Nullable(^JobsRetIDByGestureBlock)(__kindof UIGestureRecognizer *_Nullable data);
typedef id _Nullable(^JobsRetIDBySELBlock)(SEL _Nullable data);
typedef id _Nullable(^JobsRetIDByStrBlock)(__kindof NSString *_Nullable data);
typedef id _Nullable(^JobsRetIDByTwoIDBlock) (Jobs_2_Arguments);
typedef id _Nullable(^JobsRetIDByVoidBlock)(void);
typedef int(^JobsRetIntByIDBlock)(id _Nullable data);
typedef int(^JobsRetIntByIntBlock)(int data);
typedef long(^JobsRetLongByIDBlock)(id _Nullable data);
typedef NSInteger(^JobsRetNSIntegerByIDBlock)(id _Nullable data);
typedef NSUInteger(^JobsRetNSUIntegerByIDBlock)(id _Nullable data);
typedef short(^JobsRetShortByIDBlock)(id _Nullable data);
typedef CGSize(^JobsRetSizeByNSIntegerBlock)(NSInteger data);
typedef CGSize(^JobsRetSizeByUIntegerBlock)(NSUInteger data);
typedef unsigned char(^JobsRetUnsignedCharByIDBlock)(id _Nullable data);
typedef unsigned int(^JobsRetUnsignedIntByIDBlock)(id _Nullable data);
typedef unsigned long(^JobsRetUnsignedLongByIDBlock)(id _Nullable data);
typedef unsigned long long(^JobsRetUnsignedLongLongByIDBlock)(id _Nullable data);
typedef unsigned short(^JobsRetUnsignedShortByIDBlock)(id _Nullable data);
typedef void(^SDWebImageNoParamsBlock)(void);
typedef void(^jobsByBOOLBlock)(BOOL data);
typedef void(^jobsByBtnConfigBlock)(__kindof UIButtonConfiguration * _Nullable config) API_AVAILABLE(ios(15.0), tvos(15.0)) API_UNAVAILABLE(watchos);
typedef void(^jobsByCABasicAnimationBlock)(__kindof CABasicAnimation *_Nullable animation);
typedef void(^jobsByCAKeyframeAnimationBlock)(__kindof CAKeyframeAnimation *_Nullable animation);
typedef void(^jobsByCharBlock)(char data);
typedef void(^jobsByCtrlBlock)(__kindof UIControl *_Nullable ctrl);
typedef void(^jobsByDoubleBlock)(double data);
typedef void(^jobsByFloatBlock)(float data);
typedef void(^jobsByGestureRecognizerBlock)(__kindof UIGestureRecognizer *_Nullable gesture);
typedef void(^jobsByIDBlock)(id _Nullable data);
typedef void(^jobsByIPApiModelBlock)(IPApiModel *_Nullable model);
typedef void(^jobsByIntBlock)(int data);
typedef void(^jobsByIpifyModelBlock)(IpifyModel *_Nullable model);
typedef void(^jobsByIpinfoModelBlock)(IpinfoModel *_Nullable model);
typedef void(^jobsByLongBlock)(long data);
typedef void (^jobsByLuckyWheelSegmentAndLPGesturerBlock)(Jobs_LuckyWheelSegment_LPGestureRecognizer_Arguments);
typedef void (^jobsByLuckyWheelSegmentBlock)(LuckyWheelSegment *_Nullable segment);
typedef void(^jobsByMutableURLRequestBlock)(__kindof NSMutableURLRequest *_Nullable request);
typedef void(^jobsByNSIntegerBlock)(NSInteger data);
typedef void(^jobsByNSUIntegerBlock)(NSUInteger data);
typedef void(^jobsByResponseModelBlock)(JobsResponseModel *_Nullable model);
typedef void(^jobsBySELBlock)(SEL _Nullable data);
typedef void(^jobsByShortBlock)(short data);
typedef void(^jobsByStrBlock)(__kindof NSString *_Nullable string);
typedef void(^jobsByTwoIDBlock) (Jobs_2_Arguments);
typedef void(^jobsByUnsignedCharBlock)(unsigned char data);
typedef void(^jobsByUnsignedIntBlock)(unsigned int data);
typedef void(^jobsByUnsignedLongBlock)(unsigned long data);
typedef void(^jobsByUnsignedLongLongBlock)(unsigned long long data);
typedef void(^jobsByUnsignedShortBlock)(unsigned short data);
typedef void(^jobsByVoidBlock)(void);
typedef void(^jobsByYTKBatchRequestBlock)(__kindof YTKBatchRequest *_Nullable data);
typedef void(^jobsByYTKChainRequestBlock)(YTKChainRequest *_Nullable chainRequest);
typedef LZTabBarConfig *_Nullable(^tabBarBlock)(LZTabBarConfig * _Nonnull config);
// JOBS_FUNCTIONAL_BLOCK_FORWARD_AUTOGEN_END

#endif /* JobsBlockHeader_h */
