//
//  UIFont+Extras.m
//  JobsOCBaseConfigDemo
//
//  Created by Jobs on 2020/11/4.
//

#import "UIFont+Extras.h"

@implementation UIFont (Extras)
/// 打印全员字体
+(JobsRetArrByVoidBlock _Nonnull)getAvailableFont{
    return ^NSMutableArray <NSString *>*_Nullable(){
        NSMutableArray <NSString *>*fontNamesMutArr = NSMutableArray.array;
        printf("=== 打印全员字体 === \n");
        for (NSString *fontFamilyName in UIFont.familyNames) {
            printf("--- %s--- \n",fontFamilyName.UTF8String);
            [fontNamesMutArr addObjectsFromArray:[UIFont fontNamesForFamilyName:fontFamilyName]];
            for (NSString *fontName in [UIFont fontNamesForFamilyName:fontFamilyName]) {
                printf("%s\n",fontName.UTF8String);
            }
        };return fontNamesMutArr;
    };
}
/// 打印外援字体
+(JobsRetArrByVoidBlock _Nonnull)foreignAidFontName{
    return ^NSMutableArray <NSString *>*_Nullable(){
        /// 苹果可能每次发布版本会添加一些字体，这个时候需要对这个已知的字体库进行同步升级
        /// 系统自带的字体合集
        NSArray *sysFontNameArr = jobsMakeMutArr(^(NSMutableArray * _Nullable data) {
            data
                .add(@"AcademyEngravedLetPlain")
                .add(@"AlNile")
                .add(@"AlNile-Bold")
                .add(@"AmericanTypewriter")
                .add(@"AmericanTypewriter-Light")
                .add(@"AmericanTypewriter-Semibold")
                .add(@"AmericanTypewriter-Bold")
                .add(@"AmericanTypewriter-Condensed")
                .add(@"AmericanTypewriter-CondensedLight")
                .add(@"AmericanTypewriter-CondensedBold")
                .add(@"AppleColorEmoji")
                .add(@"AppleSDGothicNeo-Regular")
                .add(@"AppleSDGothicNeo-Thin")
                .add(@"AppleSDGothicNeo-UltraLight")
                .add(@"AppleSDGothicNeo-Light")
                .add(@"AppleSDGothicNeo-Medium")
                .add(@"AppleSDGothicNeo-SemiBold")
                .add(@"AppleSDGothicNeo-Bold")
                .add(@"AppleSymbols")
                .add(@"ArialMT")
                .add(@"Arial-ItalicMT")
                .add(@"Arial-BoldMT")
                .add(@"Arial-BoldItalicMT")
                .add(@"ArialHebrew")
                .add(@"ArialHebrew-Light")
                .add(@"ArialHebrew-Bold")
                .add(@"ArialRoundedMTBold")
                .add(@"Avenir-Book")
                .add(@"Avenir-Roman")
                .add(@"Avenir-BookOblique")
                .add(@"Avenir-Oblique")
                .add(@"Avenir-Light")
                .add(@"Avenir-LightOblique")
                .add(@"Avenir-Medium")
                .add(@"Avenir-MediumOblique")
                .add(@"Avenir-Heavy")
                .add(@"Avenir-HeavyOblique")
                .add(@"Avenir-Black")
                .add(@"Avenir-BlackOblique")
                .add(@"AvenirNext-Regular")
                .add(@"AvenirNext-Italic")
                .add(@"AvenirNext-UltraLight")
                .add(@"AvenirNext-UltraLightItalic")
                .add(@"AvenirNext-Medium")
                .add(@"AvenirNext-MediumItalic")
                .add(@"AvenirNext-DemiBold")
                .add(@"AvenirNext-DemiBoldItalic")
                .add(@"AvenirNext-Bold")
                .add(@"AvenirNext-BoldItalic")
                .add(@"AvenirNext-Heavy")
                .add(@"AvenirNext-HeavyItalic")
                .add(@"AvenirNextCondensed-Regular")
                .add(@"AvenirNextCondensed-Italic")
                .add(@"AvenirNextCondensed-UltraLight")
                .add(@"AvenirNextCondensed-UltraLightItalic")
                .add(@"AvenirNextCondensed-Medium")
                .add(@"AvenirNextCondensed-MediumItalic")
                .add(@"AvenirNextCondensed-DemiBold")
                .add(@"AvenirNextCondensed-DemiBoldItalic")
                .add(@"AvenirNextCondensed-Bold")
                .add(@"AvenirNextCondensed-BoldItalic")
                .add(@"AvenirNextCondensed-Heavy")
                .add(@"AvenirNextCondensed-HeavyItalic")
                .add(@"Baskerville")
                .add(@"Baskerville-Italic")
                .add(@"Baskerville-SemiBold")
                .add(@"Baskerville-SemiBoldItalic")
                .add(@"Baskerville-Bold")
                .add(@"Baskerville-BoldItalic")
                .add(@"BodoniSvtyTwoITCTT-Book")
                .add(@"BodoniSvtyTwoITCTT-BookIta")
                .add(@"BodoniSvtyTwoITCTT-Bold")
                .add(@"BodoniSvtyTwoOSITCTT-Book")
                .add(@"BodoniSvtyTwoOSITCTT-BookIt")
                .add(@"BodoniSvtyTwoOSITCTT-Bold")
                .add(@"BodoniSvtyTwoSCITCTT-Book")
                .add(@"BodoniOrnamentsITCTT")
                .add(@"BradleyHandITCTT-Bold")
                .add(@"ChalkboardSE-Regular")
                .add(@"ChalkboardSE-Light")
                .add(@"ChalkboardSE-Bold")
                .add(@"Chalkduster")
                .add(@"Charter-Roman")
                .add(@"Charter-Italic")
                .add(@"Charter-Bold")
                .add(@"Charter-BoldItalic")
                .add(@"Charter-Black")
                .add(@"Charter-BlackItalic")
                .add(@"Cochin")
                .add(@"Cochin-Italic")
                .add(@"Cochin-Bold")
                .add(@"Cochin-BoldItalic")
                .add(@"Copperplate")
                .add(@"Copperplate-Light")
                .add(@"Copperplate-Bold")
                .add(@"Courier")
                .add(@"Courier-Oblique")
                .add(@"Courier-Bold")
                .add(@"Courier-BoldOblique")
                .add(@"CourierNewPSMT")
                .add(@"CourierNewPS-ItalicMT")
                .add(@"CourierNewPS-BoldMT")
                .add(@"CourierNewPS-BoldItalicMT")
                .add(@"Damascus")
                .add(@"DamascusLight")
                .add(@"DamascusMedium")
                .add(@"DamascusSemiBold")
                .add(@"DamascusBold")
                .add(@"DevanagariSangamMN")
                .add(@"DevanagariSangamMN-Bold")
                .add(@"Didot")
                .add(@"Didot-Italic")
                .add(@"Didot-Bold")
                .add(@"DINAlternate-Bold")
                .add(@"DINCondensed-Bold")
                .add(@"EuphemiaUCAS")
                .add(@"EuphemiaUCAS-Italic")
                .add(@"EuphemiaUCAS-Bold")
                .add(@"Farah")
                .add(@"Futura-Medium")
                .add(@"Futura-MediumItalic")
                .add(@"Futura-Bold")
                .add(@"Futura-CondensedMedium")
                .add(@"Futura-CondensedExtraBold")
                .add(@"Galvji")
                .add(@"Galvji-Bold")
                .add(@"GeezaPro")
                .add(@"GeezaPro-Bold")
                .add(@"Georgia")
                .add(@"Georgia-Italic")
                .add(@"Georgia-Bold")
                .add(@"Georgia-BoldItalic")
                .add(@"GillSans")
                .add(@"GillSans-Italic")
                .add(@"GillSans-Light")
                .add(@"GillSans-LightItalic")
                .add(@"GillSans-SemiBold")
                .add(@"GillSans-SemiBoldItalic")
                .add(@"GillSans-Bold")
                .add(@"GillSans-BoldItalic")
                .add(@"GillSans-UltraBold")
                .add(@"GranthaSangamMN-Regular")
                .add(@"GranthaSangamMN-Bold")
                .add(@"Helvetica")
                .add(@"Helvetica-Oblique")
                .add(@"Helvetica-Light")
                .add(@"Helvetica-LightOblique")
                .add(@"Helvetica-Bold")
                .add(@"Helvetica-BoldOblique")
                .add(@"HelveticaNeue")
                .add(@"HelveticaNeue-Italic")
                .add(@"HelveticaNeue-UltraLight")
                .add(@"HelveticaNeue-UltraLightItalic")
                .add(@"HelveticaNeue-Thin")
                .add(@"HelveticaNeue-ThinItalic")
                .add(@"HelveticaNeue-Light")
                .add(@"HelveticaNeue-LightItalic")
                .add(@"HelveticaNeue-Medium")
                .add(@"HelveticaNeue-MediumItalic")
                .add(@"HelveticaNeue-Bold")
                .add(@"HelveticaNeue-BoldItalic")
                .add(@"HelveticaNeue-CondensedBold")
                .add(@"HelveticaNeue-CondensedBlack")
                .add(@"HiraMaruProN-W4")
                .add(@"HiraMinProN-W3")
                .add(@"HiraMinProN-W6")
                .add(@"HiraginoSans-W3")
                .add(@"HiraginoSans-W6")
                .add(@"HiraginoSans-W7")
                .add(@"HoeflerText-Regular")
                .add(@"HoeflerText-Italic")
                .add(@"HoeflerText-Black")
                .add(@"HoeflerText-BlackItalic")
                .add(@"Kailasa-Bold")
                .add(@"Kefa-Regular")
                .add(@"KhmerSangamMN")
                .add(@"KohinoorBangla-Regular")
                .add(@"KohinoorBangla-Light")
                .add(@"KohinoorBangla-Semibold")
                .add(@"KohinoorDevanagari-Regular")
                .add(@"KohinoorDevanagari-Light")
                .add(@"KohinoorDevanagari-Semibold")
                .add(@"KohinoorGujarati-Regular")
                .add(@"KohinoorGujarati-Light")
                .add(@"KohinoorGujarati-Bold")
                .add(@"KohinoorTelugu-Regular")
                .add(@"KohinoorTelugu-Light")
                .add(@"KohinoorTelugu-Medium")
                .add(@"LaoSangamMN")
                .add(@"MalayalamSangamMN")
                .add(@"MalayalamSangamMN-Bold")
                .add(@"MarkerFelt-Thin")
                .add(@"MarkerFelt-Wide")
                .add(@"Menlo-Regular")
                .add(@"Menlo-Italic")
                .add(@"Menlo-Bold")
                .add(@"Menlo-BoldItalic")
                .add(@"MyanmarSangamMN")
                .add(@"MyanmarSangamMN-Bold")
                .add(@"Noteworthy-Light")
                .add(@"Noteworthy-Bold")
                .add(@"NotoNastaliqUrdu")
                .add(@"NotoNastaliqUrdu-Bold")
                .add(@"NotoSansKannada-Regular")
                .add(@"NotoSansKannada-Bold")
                .add(@"NotoSansMyanmar-Regular")
                .add(@"NotoSansMyanmar-Bold")
                .add(@"NotoSansOriya")
                .add(@"NotoSansOriya-Bold")
                .add(@"Optima-Regular")
                .add(@"Optima-Italic")
                .add(@"Optima-Bold")
                .add(@"Optima-BoldItalic")
                .add(@"Optima-ExtraBlack")
                .add(@"Palatino-Roman")
                .add(@"Palatino-Italic")
                .add(@"Palatino-Bold")
                .add(@"Palatino-BoldItalic")
                .add(@"Papyrus")
                .add(@"Papyrus-Condensed")
                .add(@"PartyLetPlain")
                .add(@"PingFangHK-Ultralight")
                .add(@"PingFangHK-Thin")
                .add(@"PingFangHK-Light")
                .add(@"PingFangHK-Regular")
                .add(@"PingFangHK-Medium")
                .add(@"PingFangHK-Semibold")
                .add(@"PingFangSC-Ultralight")
                .add(@"PingFangSC-Thin")
                .add(@"PingFangSC-Light")
                .add(@"PingFangSC-Regular")
                .add(@"PingFangSC-Medium")
                .add(@"PingFangSC-Semibold")
                .add(@"PingFangTC-Ultralight")
                .add(@"PingFangTC-Thin")
                .add(@"PingFangTC-Light")
                .add(@"PingFangTC-Regular")
                .add(@"PingFangTC-Medium")
                .add(@"PingFangTC-Semibold")
                .add(@"SavoyeLetPlain")
                .add(@"SinhalaSangamMN")
                .add(@"SinhalaSangamMN-Bold")
                .add(@"SnellRoundhand")
                .add(@"SnellRoundhand-Bold")
                .add(@"SnellRoundhand-Black")
                .add(@"Symbol")
                .add(@"TamilSangamMN")
                .add(@"TamilSangamMN-Bold")
                .add(@"TeluguSangamMN")
                .add(@"TeluguSangamMN-Bold")
                .add(@"Thonburi")
                .add(@"Thonburi-Light")
                .add(@"Thonburi-Bold")
                .add(@"TimesNewRomanPSMT")
                .add(@"TimesNewRomanPS-ItalicMT")
                .add(@"TimesNewRomanPS-BoldMT")
                .add(@"TimesNewRomanPS-BoldItalicMT")
                .add(@"TrebuchetMS")
                .add(@"TrebuchetMS-Italic")
                .add(@"TrebuchetMS-Bold")
                .add(@"Trebuchet-BoldItalic")
                .add(@"Verdana")
                .add(@"Verdana-Italic")
                .add(@"Verdana-Bold")
                .add(@"Verdana-BoldItalic")
                .add(@"ZapfDingbatsITC")
                .add(@"Zapfino");
        });
        NSMutableArray <NSString *>*temp = NSMutableArray.array;
        for (NSString *string in UIFont.getAvailableFont()) {
            if (!sysFontNameArr.containsObject(string)) {
                temp.add(string);
            }
        }
        printf("--- 外来字体为 --- \n");
        for (NSString *string in temp) {
            printf("%s \n",string.UTF8String);
        };return temp;
    };
}

@end
